### ISSUE TITLE
切換輸入法自動刪除未成字的注音

### ISSUE THREAD

**Issue by ShikiSuen** [ShikiSuen/vChewing-CHS#109]
似乎是微軟新注音的做法。

macOS 內建的 InputMethodKit 會在摁 CapsLock 的情況下不由分說地將螢幕上的內文組字區就那樣遞交出去。
目前還沒找到針對該行為的攔截方法。

暫時先開工單備忘。

**Comment by ShikiSuen** [comment]
@qqq89513 該功能在任何一款 macOS 輸入法內都無法擴充，除非該輸入法放棄使用「內文組字區」的設計。

當輸入法使用 client.setMarkedText() 修改內文組字區的顯示內容時，輸入法只是將這些資料交給客體應用（也就是接收文字輸入的 app）而已。突然切換掉輸入法的話，相當於輸入法與客體之間斷開連線，已經 setMarkedText() 的內容不屬於輸入法的掌控範圍。

按道理來講，輸入法可以實作 IMKInputController.inputControllerWillClose() 來讓輸入法在被切換掉之前做些什麼。然而，根據我剛才的測試結果表明，InputMethodKit 出於自身程式設計缺陷的原因，並不會在一個輸入法被切換掉或關掉的時候呼叫這個函式。

結論：如果硬要解決 https://github.com/openvanilla/McBopomofo/issues/336 這個問題的話，需要使用一個單獨的工具提示浮窗（類似於微軟新注音 2007 及舊版微軟新注音的設計）、來顯示注拼槽的內容。所有在內文組字區內顯示的文字，都會在輸入法被切換出去時被遞交出去，無一倖免。

**Comment by ShikiSuen** [comment]
該問題的解決需要在 deactivateServer() 以及 commitComposition() 的時候插入一個前置處理：「先清空 phonabet composer、再重新 buildInputtingState 交給 ctlInputMethod.handle(state:) 處理」。

於是 @qqq89513 在上游提的這個問題可以解決了：https://github.com/openvanilla/McBopomofo/issues/336

**Comment by ShikiSuen** [comment]
已實裝該功能，將於 2.3.0 版推送。

**Comment by qqq89513** [comment]
這個實現願望的速度有點快

**Comment by ShikiSuen** [comment]
@qqq89513 我們就是比上游快。上游 Zonble 還造謠說我們「[直接暴力攔截「所有」的硬體事件](https://github.com/vChewing/vChewing-macOS/issues/116)」呢。
問題是他們連給自己小麥注音做 Sandbox 處理的膽量都沒有。

**Comment by ShikiSuen** [comment]
@qqq89513 上游劉燈已經對小麥注音推送了針對該問題的更正。他們用的是他們自己的方法。
