### ISSUE TITLE
[IMK][UI/UX] 暗色模式的選字框，仍然使用亮色模式的白色外框

### ISSUE THREAD

**Issue by pan93412** [ShikiSuen/vChewing-CHS#110]
## 系統版本資訊

| 類型     | 版本             |
| -------- | ---------------- |
| macOS    | 12.5.1 (ARM64)   |
| vChewing | 2.0.0 Build 2002 |

## 開發道場設定

<img width="652" alt="開發道場設定：有啟用 IMK 和 langIdentifier" src="https://user-images.githubusercontent.com/28441561/186483869-08bb1e2a-5427-480e-ba31-a21b540bf141.png">

## 名詞定義

<img width="450" alt="Issue 名詞定義。單字框即為選中之文字；單字框背景色是選中單字藍色外的背景色，選字框包含一或多個單字框。" src="https://user-images.githubusercontent.com/28441561/186480081-6c22f44e-aa10-4090-9fc8-1bde0cad3a11.png">

## 最初發現點

亮色模式下，「單字框背景色」和「選字框」的背景色是相同的：

<img width="430" alt="亮色模式很正常！" src="https://user-images.githubusercontent.com/28441561/186480301-c0de4d74-3f69-4cc4-8f96-755dbdd1a381.png">

然而在暗色模式下，「單字框背景色」與「選字框」背景色有挺明顯的顏色差距：

<img width="558" alt="暗色模式的單字框背景色是黑色，而選字框背景框是深灰。" src="https://user-images.githubusercontent.com/28441561/186479181-8865e883-3c98-4ab8-8609-b773ff462320.png">

這裡附上暗色模式選字框相關的色碼，希望能協助 debug。辛苦作者了！

<img width="463" alt="單字框背景色：#1E1F1E；選字框背景色：#262724" src="https://user-images.githubusercontent.com/28441561/186480959-ae107169-33fd-45b1-8786-69522fda4f6e.png">

## 後續發現

剛才切成 Apple 內建的「繁體注音」之後，發現這似乎是 Apple 故意為之的？不過 vChewing，跟繁體注音的輸入框有個小差別：後者似乎沒有白色 border，前者有，所以似乎就顯得比較不協調？

<img width="447" alt="繁體注音也有類似問題。" src="https://user-images.githubusercontent.com/28441561/186481710-cf1c8ce6-6e7f-4dc7-a047-32f9bf0d6b66.png">

<img width="436" alt="亮色模式的繁體注音，供實作參考。" src="https://user-images.githubusercontent.com/28441561/186482350-f4b48fef-216e-4cdf-a305-443e5155278c.png">

**Comment by ShikiSuen** [comment]
Apple 內建的注音輸入法的 IMK 選字窗不是 macOS 內建 IMK 模組的 IMKCandidates 型別的選字窗，而是其未公開的分支變種。其暗色選字窗沒有出現亮邊，可能需要問 Apple 中文輸入法團隊的 @xhacker，但他可能會受制於 Apple 公司的規章制度、而無法提供某些觀點與言論。

而威注音輸入法用的 IMK 選字窗是直接從 IMKCandidates 使用其公版方案。IMKCandidates 並未開放「允許訂製如您所說的那些色彩細節」的選項，且很多官方開放的 API 都還是壞掉的。

所以您這個工單可能無法實現，除非將來我專門學了 SwiftUI 之後用 SwiftUI 重新寫一個跟 IMK 選字窗差不多的東西。只是，IMK 矩陣選字窗的體驗實在太特別，導致對其行為體驗做黑盒分析的過程非常困難（比給這個輸入法設計注拼引擎時對之前 OVMandarin 的黑盒分析還要困難）。

P.S.: OVMandarin 的 C++ 我看不懂，所以才說我做的是黑盒分析。之後設計的鐵恨注拼引擎的內部機理與 OVMandarin 完全不同。

**Comment by ShikiSuen** [comment]
P.S.: 高亮的候選字的藍色底色周圍的不透明的部分 (controlBackgroundColor 被靜態引用話就是這樣) 應該是 Bug。
你在系統的輔助選項當中關掉透明效果之後，你會發現這個顏色跟視窗顏色一致（因為視窗顏色也是 controlBackgroundColor 只是會響應系統桌布的總體顏色、而出現某些細微的變化，屬於對 controlBackgroundColor 的動態引用）。

**Comment by ShikiSuen** [comment]
另外呢，你說的亮色邊框，其實是 macOS 12 開始的 dark mode 模式下的 NSWindow 的標準形態（除非這個 Windows 的樣式是 tooltip / floating panel 這種的……我很久沒碰 NSWindow 了，不太記得這些複雜的小稱謂）。
