### ISSUE TITLE
就 Zonble 對威注音 Shift 中英文切換功能的不實發言一事的澄清聲明

### ISSUE THREAD

**Issue by ShikiSuen** [ShikiSuen/vChewing-CHS#116]
威注音輸入法的 Shift 中英文切換功能所依賴的 Shift 按鍵判定開關繼承自業火五筆輸入法。
該方案不需要額外開放 macOS 系統的輔助權限、不需要跳出 IMK 框架，也就不會存在 Zonble 所講的那種情況。
相關技術細節請洽該檔案：https://github.com/vChewing/vChewing-macOS/blob/main/Source/3rdParty/Qwertyyb/ShiftKeyUpChecker.swift

釐清事實再講話，也是一條該有的道德紅線。

P.S.: Zonble 狂言備份（只允許自己亂講，不允許對方就地澄清）：
<img width="932" alt="image" src="https://user-images.githubusercontent.com/3164826/187363851-9e8b90a7-33e0-4cd5-81a4-a801019f21a0.png">

案發現場是在上游的 @aiex718 的這個工單 https://github.com/openvanilla/McBopomofo/issues/337

**Comment by ShikiSuen** [comment]
@aiex718 感謝您講公道話。
威注音的 codebase 任您 trace，且並未用到全局鍵盤監聽（因為這種監聽是需要使用者親自手動開放才會有的）。
與 Shift 鍵盤監聽有關的程式部分已經在這篇討論串的頂樓給出 URL。

**Comment by aiex718** [comment]
@ShikiSuen 感謝您提供檔案連結，先Star此專案後續有時間再研究。

另外稍微瀏覽了一下討論區，此專案與小麥輸入法似乎有不少歷史，個人無意評論、挑起任何過往事件。
僅感謝各位開發者的心力，開發這些順手好用的輸入法。

**Comment by ShikiSuen** [comment]
@aiex718 以下內容您聽聽就好，不用太當真。

小麥的問題已經不只是與威注音專案的不和了，而是 Zonble 已經魔怔到連外來 Bug 修正 PR 也一律拒絕的地步：
https://github.com/openvanilla/McBopomofo/pull/333

P.S.: 就目前的狀況來看，Lukhnos 現在的樣子反而好像比 Zonble 更開放些？至少他有在仔細聽您的需求。

**Comment by ShikiSuen** [comment]
@aiex718 目前的 Shift 事件偵測機制在威注音輸入法內的實作可能還有點問題。
有人抱怨過這些，只是我個人沒有遇到過就是了。
如果您有遇到的話，歡迎再開工單。
