### ISSUE TITLE
已處理：將 zonble 新引入的用戶詞彙系統進行改造，使簡繁體中文模式的用戶自訂語彙系統彼此分離。

### ISSUE THREAD

**Issue by ShikiSuen** [ShikiSuen/vChewing-CHS#13]
目前進度是在這裡：
https://github.com/ShikiSuen/vChewing-macOS/tree/dev/userphrases

我暫時沒想明白該怎麼將簡繁體中文的自訂詞庫給分開存放。

用以解決該問題的 commit 名稱為「#13 UserPhrases // CHS mode compatibility.」

**Comment by ShikiSuen** [comment]
我自己寫了一版：https://github.com/ShikiSuen/vChewing-macOS/tree/dev/userphrases-shikimessup
只是方法有點笨。我沒搞明白怎樣將既有函數改造成多功能函數的方法，就只能將函數複製一份重新起名。

**Comment by hirakujira** [comment]
[15200f60](https://github.com/ShikiSuen/vChewing-macOS/commit/1520f60027a1b6a81a86bb34077cad5ae647fa49#diff-309d238acd32fe4080dc9fca181ef61d3736da78f239f69c90e048b37eb8abe1L336) 把 #11 的修正給刪掉了，請問這是正常的情形嗎？

**Comment by ShikiSuen** [comment]
@hirakujira 那是我搞錯。已經在「Shiki: UserPhrases // Fix a regression of UOM.」這個 Commit 內嘗試補回。請審閱。

---
因為有些參數定義寫在 if 內的話就無法作用於 if 的花括弧外，所以我的修正比較笨、也沒什麼好方法可以讓源碼保持整潔。

**Comment by ShikiSuen** [comment]
備忘：下一個 commit 名稱：
Hiraku #13: UserPhrases // Optimize the CHS Compatibility Patch.

**Comment by ShikiSuen** [comment]
記錄一下目前的狀況以備忘：
皮樂遇到了目前用戶詞庫無權讀取的問題（macOS 12.1，威注音與小麥注音同時出現該問題）。
我借來一台 macOS 10.13 的電腦測試，沒能重現該問題。
皮樂決定擇日私下排查之。

考慮到這有可能是 LLVM 的 ObjC 編譯器所無法捕獲的 bug 導致的問題，
我先開個分支嘗試同步小麥注音那邊 swift 化的狀態。
根據 zonble 目前在小麥注音關於他對 swfit 觀點的答覆來看，
可以推測他很有可能在用 swift 重寫內容時順手修正了一些可能存在錯誤的寫法。

**Comment by ShikiSuen** [comment]
Case finished and closed. Thanks to Hiraku for his technical reinforcement.
