### ISSUE TITLE
2.8.5 SP1 版, 在基礎鍵盤佈局為『Apple 倚天注音鍵盤佈局』時, 選字視窗的 1, 2 號字選取錯誤

### ISSUE THREAD

**Issue by DenniesChangWT** [ShikiSuen/vChewing-CHS#167]
在 2.8.5 SP1 版當中, 把設定中的『鍵盤設定->基礎鍵盤佈局』設定為『Apple倚天注音鍵盤佈局(傳統)』

此時, 在任何應用程式中, 輸入文字後, 進入選字視窗時, 選擇任何一行候選字的編號 1 或編號 2 時, 都會
套用到編號 6 的候選字.

此時並未啟用 IMK 選字視窗, 如果啟用 IMK 選字窗則無此問題.
https://user-images.githubusercontent.com/87064015/193500517-82472d77-6188-41a7-b489-1283e3671cf3.mov

**Comment by ShikiSuen** [comment]
我這邊推測該問題可能與 AppleKeyboardConverter 的用法失誤有關。

暫時對倚天傳統鍵盤使用者們給出針對田所選字窗的保守治療方案（會犧牲掉螢幕小鍵盤的倚天注音顯示支援）：
![image](https://user-images.githubusercontent.com/3164826/193501564-d2b25371-16dc-4201-9bd1-f01e0dd80236.png)

**Comment by ShikiSuen** [comment]
@DenniesChangWT 該問題已於 2.8.5 SP2 解決。
由於網路問題，安裝包無法上傳至 GitHub。請洽 Gitee 下載：
https://gitee.com/vChewing/vChewing-macOS/releases/tag/2.8.5
