### ISSUE TITLE
[2.9.3 SP2] shift + 字母鍵輸入英文使處於可選字狀態的中文字消失

### ISSUE THREAD

**Issue by MiliChang** [ShikiSuen/vChewing-CHS#194]
**快速分類**
請問您遇到的是：

- [ ] 輸入法崩潰或正在接受文字輸入的應用程式崩潰
- [x] 輸入法叫不出來，或無法正確敲出中文
- [ ] 無法切換至特定功能的啟用/停用狀態
- [ ] 輸入法效能有問題（執行速度太慢/電腦發燙）
- [ ] 輸入法應用程式介面顯示不正常（IMK 選字窗的應用介面美術瑕疵恕不受理，因為是 Apple 負責的）
- [ ] 輸入法亂放屁（請確保偏好設定內的廉恥模式的勾沒有被去掉）
- [ ] 其他

**問題發生步驟**
請問您是怎麼遇到這個問題的？像是：

1. 輸入法輸入中文，使其處於選字狀態
2. shift + 字母鍵，處於選字狀態的中文字會全部消失

**預期正常狀況**
您覺得這是不正常的狀況，那您覺得正常結果應該是…？
輸入英文後，處於選字狀態的中文字應該如同按下 Enter，使其正常輸出。

**電腦環境**
請問您在怎樣的環境遇到這個問題？

- 威注音版本：2.9.3 SP2
- 注音排列與基礎鍵盤佈局：（在偏好設定視窗的「鍵盤設定」內可以查詢到）
    <img width="652" alt="image" src="https://user-images.githubusercontent.com/18565358/198175049-18ef0b5e-1ce4-4784-aaf5-89bb291655fc.png">
- macOS 版本：12.6
- 在哪個應用程式中打字遇到問題：Chrome, Skype ... 都會
- 電腦機種：Macbook PRO with Apple Silicon CPU
- 其他特殊設備：無
- 特殊設定：無，某次更新後出現的問題

**其他**
其他你覺得問題發生的疑點，或其他你想跟威注音開發團隊說的話。
感謝，辛苦了！威注音是最好用的中文輸入法。

**Comment by ShikiSuen** [comment]
請問您是否有開啟逐字選字模式？
我這邊測試發現在關閉逐字選字模式的時候 是在 inputting 狀態下（而非 candidate 狀態下）用 Shift 輸入英文字會導致該問題。

**Comment by ShikiSuen** [comment]
該問題已解決。相關修正會隨接下來的 2.9.4 版推送。結案。

**Comment by sheclare** [comment]
同樣問題
是更新成2.8.9才出現
如[錄影檔](https://drive.google.com/file/d/1V3X4DdwDII_UnKMMTLBJVOQ8g6rD6Dvv/view?usp=sharing)
常常需要中英混打
所以有設置按住shift可打英文字
但打英文時，前方尚未送出的中文字會消失
並且沒有勾選  [開啟逐字選字模式]

**Comment by ShikiSuen** [comment]
@sheclare 看來還真是 2.8.9 引入的一處失誤。

P.S.: 因為眾所周知的原因，我這邊用 Google 很困難（哪怕使用虛擬專用網路）。GitHub 這邊可以直接上傳短螢幕錄影的。不過如果您是剛才有電郵給過我錄影那位的話就算了，電郵裡面的錄影我有看過。

**Comment by sheclare** [comment]
是email裡面的錄影檔～
sorry 對github還不是很熟稔～

**Comment by ShikiSuen** [comment]
@sheclare @MiliChang

2.9.4 修正已經可以下載了：
https://github.com/vChewing/vChewing-macOS/releases/tag/2.9.4

**Comment by sheclare** [comment]
非常感謝您～終於解決此問題了～～撒花
