### ISSUE TITLE
輸入時可以在組字區輸入中文時直接輸入英數? 目前若輸入中文過程中直接打英數的話，組字區會直接消失。

### ISSUE THREAD

**Issue by garylin123** [ShikiSuen/vChewing-CHS#220]
/* 請將這段文字替換為具體功能描述、以及你是否在其他具體哪款輸入法當中體驗過同樣或類似的功能。 */

**Comment by ShikiSuen** [comment]
你把正文直接清空 換成你想要的功能描述吧。

**Comment by ShikiSuen** [comment]
「輸入時可以在選字窗直接輸入英數」你可有見過其他哪款輸入法實現過這種功能？

**Comment by ShikiSuen** [comment]
另外，你注意一下：你究竟是要講 組字區 還是 選字窗？
選字窗本來就不可以接收文本輸入。

**Comment by garylin123** [comment]
抱歉，我說的是組字區。

**Comment by ShikiSuen** [comment]
@garylin123 你可能遇到了自 2.8.9 版開始引入的與此功能有關的 Bug。
請升級到 2.9.4 SP1 版再測試。

**Comment by garylin123** [comment]
解決了，謝謝！
我原本是用[2.9.3 SP2] 更新到2.9.4 SP1 就OK了。

威注音真的是一個很棒的輸入法，
更新也很頻繁

**Comment by ShikiSuen** [comment]
@garylin123 哪裡，是您不嫌棄。
