### ISSUE TITLE
[功能問題提報] 威注音下使用 Safari 開啟新分頁時 Lag、旋轉彩球約 5 秒且威注音凍結

### ISSUE THREAD

**Issue by droolinghorseye** [ShikiSuen/vChewing-CHS#240]
**摘要**
在 Safari 下使用 Command+T 開啟新分頁時，一定機率會出現 Lag、彩球旋轉，威注音選單顯示「⋯⋯」。約 3-5 秒回復正常。

**快速分類**
輸入法崩潰或正在接受文字輸入的應用程式崩潰

**問題發生步驟**
同摘要

**預期正常狀況**
切換至內建注音或英文輸入法則無此問題。

**螢幕截圖或螢幕錄製**

https://user-images.githubusercontent.com/32830717/200014058-21289af9-3511-4f81-b05d-03b22c9be3d4.mov

**電腦環境**
請問您在怎樣的環境遇到這個問題？

- 威注音版本：2.9.4
- 注音排列與基礎鍵盤佈局：Apple 標準注音鍵盤布局
- macOS 版本：13.0（22A380）
- 在哪個應用程式中打字遇到問題：Safari 16.1（18614.2.9.1.12）
- 電腦機種：MacBook Pro 14 M1 Pro
- 其他特殊設備：無關。
- 特殊設定：更換至 Apple Silicon 始發生。

**其他**
謝謝。

**Comment by ShikiSuen** [comment]
該問題很可能是機種限定問題或者 CPU 品質問題所致。
為了證實這個假說，我需要有其他持有 M1 MacBook Pro 跑 macOS 13 的使用者們協助測試。

**Comment by ShikiSuen** [comment]
之前在問題 #226 當中得出的結論是：

「(de)activateServer() 過程中不能有 setMarkedText()，否則會導致無限迴圈。」

但 PO 主的問題得同時從另一個新層面來解決。這個新層面的解決方式就是：讓 (de)activateServer() 以及 setValue() 的執行過程盡量不耗時。所以這次用了 GCD 處理、將全部的任務扔給一個新的不需要等待結束的執行緒。

Apple 應該將這部分內容寫到 documentation 當中。

**Comment by ShikiSuen** [comment]
Dealt in 2.9.6.
