### ISSUE TITLE
[功能建議] 在 shift 切換中英文輸入法時能夠永遠維持目前輸入法的中英文狀態

### ISSUE THREAD

**Issue by kaiiiz** [ShikiSuen/vChewing-CHS#260]
**痛點**
目前威注音在 shift 切換中英輸入法後，似乎沒有辦法在瀏覽器的不同 tab 中保持相同的輸入法，舉例來說：

- 先在 tab 1 開啟 google.com 在搜索欄使用 shift 切換成英文輸入法，輸入關鍵字
- 再打開一個新的 tab 2 開啟 google.com，此時輸入法不會是英文輸入法而會是中文輸入法

每次切換 tab 輸入法都會再被切換回中文覺得不是很直覺，而且並沒有一個指示說明目前輸入法的狀態是中文還是英文，導致滿常會先打出一個注音後發現目前是中文輸入法，接著才再按一次 shift 切換成英文輸入法

在 telegram 不同聊天室切換的時候也會發生這種情況。

**功能說明**
不太確定這個功能的實現是不是跟 [A. 中英切換](https://vchewing.github.io/manual/toggles.html#a-%E4%B8%AD%E8%8B%B1%E5%88%87%E6%8F%9B) 這邊敘述的實作方式有關，會不會因為資安問題會讓這個功能不太好實現？

不過最好的情況是希望可以有一個功能是能夠永遠維持目前輸入法的中英文狀態，並且在狀態欄有一個指示器能夠顯示目前中英文的狀態（類似超注音輸入法的實現方式）

以下是超注音的指示器樣式：

![image](https://user-images.githubusercontent.com/30596812/202840710-b25618ff-3ade-401b-9295-b34dfe652d76.png)

![image](https://user-images.githubusercontent.com/30596812/202840723-ac5b79d5-7e35-42bf-ac5c-3180213ee59a.png)

**替代方案**
如果以上功能難以實現，希望在狀態欄能有一個指示器能夠顯示目前中英文的狀態

**其他**
測試環境：
- Macbook Air M1
- MacOS 12.2.1
- vChewing 2.9.5 SP2
- Browser
  - MS Edge 107.0.1418.42
  - Safari 15.3 (17612.4.9.1.8)

**Comment by ShikiSuen** [comment]
很抱歉該建議得緩幾個月才能處理了。我這邊實在非常忙，目前僅有的時間都在處理「記憶體洩漏」的 bug。

目前威注音輸入法是針對不同的客體 App 分別記憶對應的中英文開關狀態的。
你是想要全系統全局統一這個狀態嗎？

超注音那種工具列顯示，我曾經有考慮過，現在感覺還是會有些複雜的樣子。
我明年有時間再想想這個功能該怎麼設計。
（工具列的圖示空間吋土吋金。）

**Comment by kaiiiz** [comment]
感謝回覆。

> 目前威注音輸入法是針對不同的客體 App 分別記憶對應的中英文開關狀態的。

我原本也是這樣預期的，如果是這樣的話瀏覽器的不同 tab 應該是要屬於相同中英文狀態的，不過目前我測試 MS Edge 以及 safari，在新增 tab 的時候這個狀態會變回中文。此外，在 telegram 的不同聊天室切換也會變回中文，不會保持都在英文。

> 你是想要全系統全局統一這個狀態嗎？

對，我覺得全局統一狀態的話，可以避免我在切換 app 的時候「猜」目前輸入法是什麼狀態，加上目前上面提到的那個非預期的中英文切換會使這個「猜」的情況更加嚴重。

**Comment by ShikiSuen** [comment]
@kaiiiz 有些瀏覽器會將每個頁籤都作為一個 IMKTextInput Client 來使用，所以才會出現「中英文開關狀態在 tab 鍵之間不同步」的情況。

無論如何，我今年是沒時間動手處理了。剛剛調查了一下，發現「新增選單列圖示」好像也沒那麼輕鬆。
我屆時再考慮一下有沒有比選單圖示更好的辦法。

**Comment by ShikiSuen** [comment]
macOS 選單列的圖示我暫時先不做。Shift 中英文切換狀態「跨客體共用」正在做，但預設不啟用。
回頭可以在輸入法偏好設定的「體驗設定」頁面內自行啟用之。
相關勾選項名稱：
```
"Share alphanumerical mode status across all clients" = "Share alphanumerical mode status across all clients";
"Share alphanumerical mode status across all clients" = "對所有客體應用共用 Shift 中英文輸入切換狀態";
"Share alphanumerical mode status across all clients" = "对所有客体应用共用 Shift 中英文输入切换状态";
"Share alphanumerical mode status across all clients" = "全ての客体アプリに英数入力モードの状態を共有";
```
