### ISSUE TITLE
[功能建議] 使用 shift 快速輸入常用半形標點符號

### ISSUE THREAD

**Issue by kaiiiz** [ShikiSuen/vChewing-CHS#262]
**痛點**
在撰寫 markdown 文件時，常常需要使用 `#`, `*`, `-` 等標點符號，然而在中文輸入法的情況下使用 shift 快速輸入符號時會輸出全形的 `＃`, `＊`, `—`，因此要輸入這些半形的標點符號時還要再切換回英文輸入法，輸入完畢後再切換回中文輸入法，不是很方便。

**功能說明**
希望可以在設定介面中設定為常用標點符號增加 shift 快速輸入的選項，若真的需要輸入全形標點，還可使用 ` 叫出標點符號的選單輸入。

目前我認為快速輸入應該要包含以下符號：
- `@` (shift + 2) 原本的輸出符號：`＠`
- `#` (shift + 3) 原本的輸出符號：`＃`
- `$` (shift + 4) 原本的輸出符號：`＄`
- `%` (shift + 5) 原本的輸出符號：`％`
- `^` (shift + 6) 原本的輸出符號：`︿`
- `&` (shift + 7) 原本的輸出符號：`＆`
- `*` (shift + 8) 原本的輸出符號：`＊`
- `-` (shift + -) 原本的輸出符號：`—`
- `=` (=) 原本的輸出符號：`＝`
- `+` (shift + =) 原本的輸出符號：`＋`

但一些經常在中文文章中使用的全形標點符號，不應被加到快速輸入的清單：
- `！` (shift + 1)
- `（` (shift + 9)
- `）` (shift + 0)
- `，` (shift + <)
- `。` (shift + >)
- `？` (shift + ?)
- `「` ([)
- `」` (])
- `、` (\\)
- `：` (shift + ;)
- `；` (shift + ')

**替代方案**
目前使用 `Ctrl+Shift+Command+H` 能夠切換要輸出全形還是半形標點，但是會針對所有標點符號都做處理，像是在打中文文章時應該很少使用 `,` 當作逗號，因此希望可以切開標點符號的快速輸入，在部分情況下輸出全形，部分情況下輸出半形，減少在全半形模式或是中英文模式切換的次數。

**其他**
更進階的功能可以設計讓使用者自定義快速輸入半形標點符號的清單應該要有哪些，不必將這個清單寫死在程式中，可以更適用於不同使用者的習慣。

**Comment by ShikiSuen** [comment]
@kaiiiz 您可以使用威注音的半形標點模式。該模式有對應的熱鍵。

**Comment by ShikiSuen** [comment]
@kaiiiz 這個需求太複雜了。就算是 Markdown，也有人可能偏好半形逗號輸入。
不然我想辦法在關掉半形標點模式時也允許輸入半形標點吧，雖然這種情況下最優先的仍舊是全形標點。

**Comment by kaiiiz** [comment]
> 就算是 Markdown，也有人可能偏好半形逗號輸入。

我認同，所以最好的情況是能夠定義這個快速輸入的清單，不過實現應該就會變得複雜許多。

> 不然我想辦法在關掉半形標點模式時也允許輸入半形標點吧，雖然這種情況下最優先的仍舊是全形標點。

這邊補充提供超注音在實作這個功能的選項，開啟「中文模式下輸入全形的中文標點」這個選項時，會將常見的中文符號（像是`，`、`。` 等以全形輸出），其餘像是 `#`, `*`, `-` 等仍然是以半形輸出。

![image](https://user-images.githubusercontent.com/30596812/203104463-f3f83abe-0eb5-4951-b347-5bc73b0ca409.png)

**Comment by ShikiSuen** [comment]
@kaiiiz 你還可以在使用者辭典內新增下述內容。
這樣會使除了 # 以外的內容被新增的內容凌權。
至於 # 失效的原因，則是因為 # 開頭的內容會被當作註釋、而在讀取時被自動忽視。此法無解。

```
= _punctuation_=
+ _punctuation_+
- _punctuation__
* _punctuation_*
& _punctuation_&
^ _punctuation_^
% _punctuation_%
$ _punctuation_$
# _punctuation_#
@ _punctuation_@
```

**Comment by ShikiSuen** [comment]
我乾脆改天更新一下 LMConsolidator 的邏輯好了：當遇到 `\#` 的組合時，不將其中的 # 視為注釋。

**Comment by kaiiiz** [comment]
今天才知道有 `_punctuation_` 這個用法，看起來用這個方式應該就可以解決這個需求了

**Comment by ShikiSuen** [comment]
@kaiiiz 這是為了方便小麥注音使用者直接遷移他們的詞庫過來用。
威注音最早期的版本使用的辭典模組引擎是自小麥注音繼承來的。
現在雖然重寫了，但為了使用者辭典格式相容性才這麼設計。

**Comment by ShikiSuen** [comment]
備忘一下修補方法：

LMAssembly 會在讀取原廠標點資料時自動生成半形標點資料。
原廠詞庫新增一處標點修正（與 `^` 有關）。

使用者辭典需由使用者自行新增：
```
= _punctuation_=
+ _punctuation_+
- _punctuation__
* _punctuation_*
& _punctuation_&
^ _punctuation_^
% _punctuation_%
$ _punctuation_$
＃ _punctuation_# -114.514
@ _punctuation_@
```

以上內容對接下來的威注音 2.9.7 生效。
