### ISSUE TITLE
[功能問題提報] 選字游標導致預設顏文字功能無法使用

### ISSUE THREAD

**Issue by aliceric27** [ShikiSuen/vChewing-CHS#311]
### **請在開新的工單之前閱讀《[故障提報與用儀器捉蟲](https://vchewing.github.io/BUGREPORT.html)》按照裡面的方法整理相關資訊、且在開工單之後電郵知會我。因各種可能原因，威注音的主程式師可能無法隨時收取 GitHub 與 Gitee 的工單提醒訊息。**

**摘要**
請簡單說明您遇到了什麼問題。這份表格雖然是中文的（我們相信注音輸入法的用戶應該都能看懂中文），但開發團隊可以使用中英文溝通，您也可以使用英文提報問題。

**快速分類**
請問您遇到的是：

- [ ] 輸入法崩潰或正在接受文字輸入的應用程式崩潰
- [ ] 輸入法叫不出來，或無法正確敲出中文
- [x] 無法切換至特定功能的啟用/停用狀態
- [ ] 輸入法效能有問題（執行速度太慢/電腦發燙）
- [ ] 輸入法應用程式介面顯示不正常（IMK 選字窗的應用介面美術瑕疵恕不受理，因為是 Apple 負責的）
- [ ] 輸入法亂放屁（請確保偏好設定內的廉恥模式的勾沒有被去掉）
- [ ] 其他

**問題發生步驟**
請問您是怎麼遇到這個問題的？像是：

1. 設定完選字游標為windows風格
2. 直接打字 日期 或 顏文字 
3. 選字框無法正確顯示當前日期與預設顏文字於候選窗

Windows風格
<img width="468" alt="image" src="https://user-images.githubusercontent.com/30149653/208240689-51556609-17a6-42f2-8830-8b8b71e4e6c5.png">

Mac風格
<img width="469" alt="image" src="https://user-images.githubusercontent.com/30149653/208240704-1e3a0928-f9b6-4b7e-ae84-c24b6161e69a.png">

**預期正常狀況**
應該顯示對應的目前日期與言文字於候選窗內

**電腦環境**
請問您在怎樣的環境遇到這個問題？

- 威注音版本：3.1.1（請填寫版本）
- 注音排列與基礎鍵盤佈局：
<img width="540" alt="image" src="https://user-images.githubusercontent.com/30149653/208240604-ecdc7da2-131d-470a-b888-36bd01da4397.png">
（在偏好設定視窗的「鍵盤設定」內可以查詢到）
- macOS 版本：12.6（請填寫版本與建置編號，例：「13.0 (22A5321d)」）
- 在哪個應用程式中打字遇到問題：所有編輯器（應用程式名稱/版本）
- 電腦機種：Macbook pro 14 m1 pro（筆電或桌機，使用 Intel 或 Apple Silicon CPU）
- 其他特殊設備：（請填寫是否有外接螢幕、特製鍵盤如非標準美式鍵盤等）
- 特殊設定：設定為mac風格則為正常（是否原本正常，改了某個系統設定後就遇到問題）

**其他**
其他你覺得問題發生的疑點，或其他你想跟威注音開發團隊說的話。

**Comment by aliceric27** [comment]
我自己犯蠢了 兩種風格的選字次序不一樣

**Comment by ShikiSuen** [comment]
<img width="855" alt="image" src="https://user-images.githubusercontent.com/3164826/208241351-acd06edd-16de-483e-8c67-0f912b780a1c.png">
@aliceric27 沒關係。

**Comment by ShikiSuen** [comment]
喔對了，威注音不支援 node-crossing，所以才會有這種疑惑。
node-crossing 只有小麥注音與奇摩注音才有。
