### ISSUE TITLE
[功能建議]關於「行為設定」裡「Shift+字母鍵」的行為

### ISSUE THREAD

**Issue by wayneljw** [ShikiSuen/vChewing-CHS#399]
您好

關於「行為設定」裡的「Shift+字母鍵」的行為...

目前有三個設定值：
0：直接鍵入內文組字區（預設）
1：直接遞交小寫字母
2：直接遞交大寫字母

【建議】
這個區塊再加一個核取方塊「當內文組字區無內容時，一律直接遞交」。

【理由】
喜歡0設定的人，「主要的原因」是：
在快速輸入中英混合的內容時，希望可以回到組字區的前面來修改中文選字，
而不要在輸入英文的過程中，就將未校對的中文字遞出了。

但是，當組字區裡無內容時，以上的「原因」是不存在的，
照理來說，在這樣的狀況下，是可以直接遞交的。

【副作用】
有些喜歡0設定的人，有另一部分原因是「希望輸入英文字母之後，可以針對大小寫、全半形來選字。」
如果因為組字區無內容就直接遞交，那麼使用者就沒機會選字了。
但使用組字區來選大小寫、全半形應該是比較少的。

【其他】
無論選擇0、1、2，當威注音輸入法啟動時，在Google試算表裡，
皆無法在儲存格「直接」輸入符號字元（例如：*、-、/ 等等）。
必須要先按一下ENTER，使游標在儲存格出現，然後才能開始輸入這些符號字元，有點小小不便。
這是與內建注音輸入法不同的地方，以上提供回饋。

謝謝。

**Comment by ShikiSuen** [comment]
我先備忘一下。(更新：已經實作完畢，需要再測試下)。

```
【其他】
無論選擇0、1、2，當威注音輸入法啟動時，在Google試算表裡，
皆無法在儲存格「直接」輸入符號字元（例如：*、-、/ 等等）。
必須要先按一下ENTER，使游標在儲存格出現，然後才能開始輸入這些符號字元，有點小小不便。
這是與內建注音輸入法不同的地方，以上提供回饋。
```
這部份不屬於我的可控範圍。（作為 IMKTextInput Client 而言的）網頁元件與輸入法 Server 的對接部分不是我能控制的。

**Comment by ShikiSuen** [comment]
我考慮了一下，這個功能不然改成這樣：

0. 直接鍵入內文組字區（預設）
1. 始終直接遞交小寫字母
2. 始終直接遞交大寫字母
3. 直接遞交小寫字母，除非組字區為空
4. 直接遞交大寫字母，除非組字區為空

這樣反而比較容易實作。

-----

另外發現這個功能之前會有「將未完成組字的注音/字根遞交出去」的故障，已經修復。

**Comment by ShikiSuen** [comment]
@wayneljw 該功能已經實裝到威注音輸入法在 GitLab China 的 dev 分支。請關注 https://twitter.com/vChewingIME 推送的今後的軟體更新資訊。

**Comment by ShikiSuen** [comment]
該工單先關閉了。

**Comment by ShikiSuen** [comment]
@wayneljw 請更新至威注音輸入法 3.4.3 版。該功能已經正式推送。
