### ISSUE TITLE
[功能建議]請問你們支援哪些拼音？還有注音鍵盤的功能建議

### ISSUE THREAD

**Issue by xayahrainie4793** [ShikiSuen/vChewing-CHS#410]
請問你們支援哪些拼音？是 http://www.pinyin.info/romanization/compare/zhuyin.html 裡面的六種拼音都支援吧？我看到你們的特色功能 https://vchewing.github.io/README.html#主要特色功能-feat 那邊有寫「華羅拼音」，華羅拼音指的應該就是國語羅馬字 https://zh.wikipedia.org/wiki/國語羅馬字 吧？國語羅馬字的聲調是直接弄在拼音上的，而不是跟其他五種拼音一樣用調號來標示聲調，所以用國語羅馬字輸入法的時候不用額外輸入聲調

建議對於拼音中出現的英文26個字母以外的字母，使用漢語拼音輸入時，ü字母用v鍵輸入，而使用威妥瑪拼音輸入時，送氣符號用q鍵輸入（q=氣），ü用v鍵輸入（至於ŭ與u跟ê與e，因為不會搞混，所以不用另外用一個鍵來輸入）

還有雙拼的部分，建議支援 https://zh.wikipedia.org/wiki/双拼 中提到的全部八種雙拼輸入法的鍵盤配置

還有精業鍵盤排列也可以提供螢幕鍵盤顯示支援，畢竟這個輸入鍵盤排列微軟新注音輸入法也有，而微軟新注音輸入法也有螢幕小鍵盤

另外對於注音輸入法，你們可以跟微軟新注音輸入法一樣，有「自訂相近音輸入」的選項（也就是把某些相近的注音，例如ㄓㄗ或ㄣㄥ等等，視為相同）以及「輸入模式自動切換」的選項（智慧型輸入模式自動切換，也就是當輸入的注音不符合讀音規則時，直接將輸入切換成英數模式，例如輸入「ㄍㄧ」會變成「eu」，以及「萬用調號字元」，可以在不確定調號時使用

還有你們的「神通」鍵盤顯示 https://vchewing.github.io/manual/arranges.html#神通-mitac 似乎有誤（有兩個ㄒ且沒有ㄡ），並且ㄩ的位置與下面的表格不符合，參考： https://zh.wikipedia.org/wiki/注音輸入法#神通注音鍵盤排列 ）

還有建議你們可以直接「CMD鍵+標點符號鍵」來直接輸入全形標點

另外幾年前我也發明了一種注音鍵盤排列，其特色為按照漢語拼音（不是威妥瑪拼音）排列，因此很方便漢語拼音的使用者盲打，完全沒有任何注音是因為字母與注音符號的形狀很像（例如ㄨ對應X，ㄚ對應Y，ㄩ對應U）或者是發音一樣（例如ㄧ對應E，ㄞ對應I，ㄒ對應C），很符合漢語拼音熟習者的思考方式，而且完全不佔用任何數字鍵跟符號鍵，輸入數字和符號的方法不用額外制訂：

與漢語拼音相同：

ㄅ=B，ㄆ=P，ㄇ=M，ㄈ=F，ㄉ=D，ㄊ=T，ㄋ=N，ㄌ=L，ㄍ=G，ㄎ=K，ㄏ=H，ㄐ=J，ㄑ=Q，ㄒ=X，ㄖ=R，ㄗ=Z，ㄘ=C，ㄙ=S，ㄚ=A，ㄛ=O，ㄜ=E

類似許氏鍵盤配置的ㄓㄔㄕ與ㄐㄑㄒ對應：

ㄓ=J，ㄔ=Q，ㄕ=X

ㄧ當聲母時為Y，當韻母時為I，ㄨ當聲母時為W，當韻母時為U，但是ㄧㄡ（iu）的ㄡ是U，ㄨㄟ（ui）的ㄟ是I，ㄡ與W、ㄟ與Y之間沒有任何關係，所以：

ㄧ=Y，ㄨ=W，ㄟ=I，ㄡ=U

ㄩ為ü，而大部分的拼音輸入法的ü都是以v鍵輸入，所以：

ㄩ=V

剩下的注音：

ㄝ=P（ㄛ=O，讓ㄛㄝ排在一起），ㄞ=K，ㄠ=L（讓ㄞㄠ排在一起），ㄢ=B，ㄣ=N，ㄤ=M（讓ㄢㄣㄤ排在一起），ㄥ=R，ㄦ=T（讓ㄥㄦ排在一起，ㄥ跟ㄖ放同一鍵不會有問題，因為ㄥ基本上不會單獨使用）

聲調：

中間五個字母DFGHJ分別代表一聲、二聲、三聲、四聲、輕聲（或者你如果很堅持，一聲要用空格鍵（微軟新注音輸入法的自訂鍵盤不能自訂一聲的位置，而只能用空格鍵），就把一聲從D鍵移到空格鍵，輕聲從J鍵移到D鍵，這樣剛好可以讓每個鍵最多只有兩個注音（包含聲調））

最後，你們也可以提供自訂注音鍵盤對應（微軟新注音輸入法就有提供），最好支援單個按鍵對應超過一個注音符號（且可能還兼具聲調），以及支援微軟新注音輸入法的自訂鍵盤不支援但倚天41鍵鍵盤與精業鍵盤都有用到的「'」鍵

**Comment by ShikiSuen** [comment]
@xayahrainie4793 華羅拼音是台灣華語羅馬音。

我先吃飯，回頭再繼續看您的這個 Issue。

**Comment by ShikiSuen** [comment]
@xayahrainie4793 

感謝您的提報。以下是今後會修正的內容：

一、神通鍵盤的 keylayout 故障（有兩個「ㄒ」且沒有「ㄡ」）。

以下內容無法實現：

一、威妥瑪拼音無法支援，因為其無法與國語注音形成一對一的映射關係。
二、威注音不支援雙拼，也不打算支援雙拼。有相關需求者請改用 RIME、或者自己製作 CIN 磁帶檔案。
三、螢幕鍵盤顯示支援是由 macOS 內部提供的。威注音有嘗試做其它佈局的螢幕鍵盤顯示支援，但配置起來空前麻煩，只能作罷。
四、「自訂相近音輸入」的邏輯實現起來會像滾雪球一樣增加專案的維護難度，且本身實現起來也很複雜。很多與此相似的特性都需要 SQL 資料庫，但我不是這方面的精通者。萬用調號字元不支援的原因也是如此。
五、「智慧型輸入模式自動切換」需要預測使用者的行為，但這往往就是很難預測的。
六、「CMD鍵+標點符號鍵」在 macOS 系統內會被很多應用程式用來當作功能熱鍵，故不宜直接佔用。
七、與「自訂注音鍵盤對應」有關的內容超出我的能力範圍，請另行聘人修改 Tekkon 注拼引擎、以滿足您的產品需求。
八、請考慮將您的這個自訂的注音鍵盤排列給一個命名、單獨制定成一份標準文稿。考慮到您的這個注音鍵盤排列方案的通用程度，我保留對此功能實作收費的權利。

**Comment by ShikiSuen** [comment]
關於神通鍵盤的佈局問題，已經轉移至工單 #411 。

目前這個工單先關閉。

**Comment by xayahrainie4793** [comment]
威妥瑪拼音可以與國語注音形成一對一的映射關係啊，例如ㄅㄚ拼成pa，ㄆㄚ則是拼成p'a，有送氣符號「'」，不要省略送氣符號就可以一對一對應了，這個送氣符號可以用Q鍵來輸入（另外ü的部分，也跟漢語拼音一樣，用V鍵來輸入）

還有華羅拼音（國語羅馬字）因為不是跟其他五種拼音一樣用調號來標示聲調，而是直接把聲調（輕聲除外）表現在拼音上，例如「海」字為hae，為原本ㄏㄞ的hai加個三聲的表現（把i改成e），所以華羅拼音的輸入法不用再帶有數字聲調

另外我覺得我設計的這個注音鍵盤排列跟星光排列 https://vchewing.github.io/manual/arranges.html#%E6%98%9F%E5%85%89%E6%8E%92%E5%88%97-starlight 很類似啊，可以說是星光排列的修改，星光排列還佔用了67890五個數字鍵，而我設計的這個注音鍵盤排列就跟許氏鍵盤與倚天26鍵鍵盤一樣，完全不占用任何數字鍵或符號鍵，所以你們可以把這個鍵盤也加進你們的鍵盤輸入配置的選項

還有，你們說「精業排列的有效性不受威注音固定支援，也就是說威注音只是嘗試對其做半吊子支援。原因在於該排列相比偽精業等排列而言浪費了三個數字按鍵、且對右手符號鍵區的過多佔用反而會帶來不便。出於研發功能矛盾等難處，威注音不對精業排列提供螢幕鍵盤顯示支援」，不過我覺得也要提供，畢竟這也是你們支援的鍵盤配置之一，你們目前總共支援10種注音鍵盤，就只有這一種沒有提供

另外你的頁面 https://vchewing.github.io/manual/arranges.html 的第一張圖 https://vchewing.github.io/manual/assets/arrangeStaticDachen-withPinyin.png 有錯誤，三聲是上聲不是陽平，四聲是去聲不是上聲，二聲是陽平不是去聲，還有酷音大千26鍵的圖 https://vchewing.github.io/manual/assets/arrangeDynamicDachenCP26.png 也跟下面的表格不一樣，二聲是在Y鍵不是在E鍵，三聲是在E鍵不是在R鍵，四聲是在R鍵不是在D鍵，輕聲是在D鍵不是在U鍵

**Comment by ShikiSuen** [comment]
@xayahrainie4793 你心情如此急切（像是在讓我完成你規定的義務似的），但你又並非我金主，所以我隨心情保留將你的 feature request 無限期延遲實現的權利。如果你看我有提前完成，那也不是給你完成的。

正好給你幾個月的時間讓你把你想講的 feature request 全部講完。但請仍舊先做好這個心理準備：你說的那種方案可能永不支援。你可以去小麥注音那邊找劉燈，看他是否樂意做這個（他們的注拼引擎是 OVMandarin）。

**Comment by ShikiSuen** [comment]
酷音大千 26 佈局的 yerd 對應大千傳統佈局的 7634。
https://github.com/chewing/libchewing/blob/master/src/common/key2pho.c
<img width="671" alt="image" src="https://user-images.githubusercontent.com/3164826/227709807-17eb101d-3ea4-45ec-ae54-06a0e2730c3a.png">

**Comment by ShikiSuen** [comment]
另：精業鍵盤在打字方面其實是完全支援的，但這會耽誤到部分常用的符號鍵的輸入。

**Comment by ShikiSuen** [comment]
威注音官方網站的下述注音鍵盤排列擷圖已經訂正：

- 酷音大千二十六鍵佈局（修正了輕聲的位置）。
- 簡體中文傳統大千拼音鍵盤佈局（聲調的中文稱謂）。
- 神通鍵盤佈局（修正了ㄡ與ㄩ的位置）。

<img width="369" alt="image" src="https://user-images.githubusercontent.com/3164826/227710826-c3be6bc6-00a5-4bb7-b498-662e041b6772.png">
<img width="373" alt="image" src="https://user-images.githubusercontent.com/3164826/227710839-a1a74191-e63e-4514-88c0-ce5e2bfd07cd.png">
<img width="373" alt="image" src="https://user-images.githubusercontent.com/3164826/227710845-60562d94-3681-41d3-b69b-6f7082d43a93.png">

**Comment by ShikiSuen** [comment]
威注音官方網站的酷音大千二十六鍵佈局的表格資料已經更正：
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/3164826/227711057-5d4138c8-71b4-40ea-aa65-5837d5f3f5ce.png">

**Comment by ShikiSuen** [comment]
鐵恨注拼引擎對酷音大千26鍵以及神通鍵盤的處理並無不妥之處。工單 #411 因此結案。

**Comment by ShikiSuen** [comment]
韋氏拼音可以做，但趙元任國語羅馬字無法實現。
原因在於鐵恨注拼引擎對聲調的處理方式。
可能 RIME 更適合用來實作對趙元任國語羅馬字的支援。

**Comment by ShikiSuen** [comment]
因為「`」鍵被威注音用作符號鍵，所以韋氏拼音的清濁分辨鍵被改為「'」鍵。

**Comment by xayahrainie4793** [comment]
你說國語羅馬字無法實現，那請問華羅拼音是什麼？你可以給我相關網站嗎？謝謝。

至於韋氏拼音的清濁分辨的部分，你也可以考慮用幾個韋氏拼音沒有用到的字母鍵（你可以從當中選一個），包括B、D、Q、X

**Comment by ShikiSuen** [comment]
@xayahrainie4793 請看這一頁：https://pinyin.thl.tw/compare?s=
我直接用這頁當中的韋氏拼音的清濁分辨記號了。

------------

這是我最後一次提醒：不要再用命令的口吻要求對方做非義務的事情。
這屬於「可以被有理有據地充分認定為不符合職人操守的言行」。
你已經連續三次觸犯該倉庫的行為守則了：https://github.com/vChewing/vChewing-macOS/blob/main/code-of-conduct.md
我比小麥注音那邊仁慈的是，我會及時提醒。他們那邊直接不吭聲，等你講夠多了直接死刑。

雖然很感謝你提報問題，但你講話方式與態度是另一回事。
你迄今為止的發言結合起來，投稿到靠北工程師，可以供全台澎金馬資工業者們笑上三個月。

**Comment by xayahrainie4793** [comment]
好的，謝謝

**Comment by xayahrainie4793** [comment]
嗨，這裡是我設計的六種鍵盤，三種靜態配置跟三種動態配置，你們可以考慮加入，謝謝。

https://sites.google.com/view/chinese-keyboard/

**Comment by ShikiSuen** [comment]
@xayahrainie4793 考慮到這些都是你自己設計的鍵盤佈局、屬於私人需求，我收費三萬新台幣。
不然我不做這個。
