### ISSUE TITLE
Tekkon: Wrong value assignment in handleEten26().

### ISSUE THREAD

**Issue by xayahrainie4793** [ShikiSuen/vChewing-CHS#414]
https://github.com/vChewing/vChewing-macOS/blob/main/Packages/vChewing_Tekkon/Sources/Tekkon/Tekkon_SyllableComposer.swift
第450行，「vowel = "ㄆ"」應該要改成「consonant = "ㄆ"」

**Comment by ShikiSuen** [comment]
我得將整個倉庫 Archive 掉，不然真要瘋掉。還有別的案子要管。

**Comment by ShikiSuen** [comment]
這個問題回頭會對 CSharp 與 Swift 版的鐵恨注拼引擎修正。但由於諸多原因無法套用至 C++ 版，所以鐵恨注拼引擎的 C++ 版無限期停止維護。

其實這個 Bug 並沒有影響使用，因為整個處理流程的後續部分有糾錯。不然的話，肯定通不過單元測試的。

先關單好了。
