### ISSUE TITLE
[功能建議]建議在主頁面增加七大拼音頁面的外部連結

### ISSUE THREAD

**Issue by xayahrainie4793** [ShikiSuen/vChewing-CHS#415]
建議在主頁面 https://vchewing.github.io/README.html 增加七大拼音的外部連結，增加兩個外部連結至 http://www.pinyin.info/romanization/compare/zhuyin.html （漢語拼音、通用拼音、國音二式、雅禮（耶魯）拼音、威妥瑪（韋式）拼音、國語羅馬字）以及 https://pinyin.thl.tw/compare （華羅拼音），你們已經有十大注音鍵盤（大千、大千26鍵、倚天、倚天26鍵、IBM、精業、偽精業、許氏、神通、星光）的頁面了 https://vchewing.github.io/manual/arranges.html 但是卻沒有七大拼音的頁面

**Comment by ShikiSuen** [comment]
一個都不打算加。
提供相關的拼音輸入支援，僅僅是為了方便習慣者。然而，敝專案並無推廣任何拼音方案之義務。
