### ISSUE TITLE
[功能建議]請問你們支援Dvorak鍵盤嗎？

### ISSUE THREAD

**Issue by xayahrainie4793** [ShikiSuen/vChewing-CHS#418]
建議你們可以多一個「支援Dvorak鍵盤」的選項，新酷音輸入法就有支援Dvorak鍵盤。

有關於Dvorak鍵盤的詳細內容見：

https://zh.wikipedia.org/wiki/%E5%BE%B7%E6%B2%83%E5%A4%8F%E5%85%8B%E9%8D%B5%E7%9B%A4

對於 https://vchewing.github.io/manual/arranges.html 中提到的10種注音鍵盤（大千傳統、大千26鍵、倚天傳統、倚天26鍵、許氏、IBM、精業、偽精業、神通、星光），其中（大千傳統、大千26鍵、IBM、精業、偽精業）這五種鍵盤的注音是單純排列注音、與英文的鍵盤完全無關的，所以他們的Dvorak鍵盤配置就跟原本的QWERTY鍵盤配置完全相同，而對於剩下的五種跟英文的鍵盤有關的注音鍵盤（倚天傳統、倚天26鍵、許氏、神通、星光）：

倚天傳統：

維持原本的注音對應的英文鍵盤，但是ㄓㄔㄕ這三個注音移到左上角的「'」「,」「.」的位置（等同於QWERTY鍵盤的QWE的位置），ㄗ移到右下角的Z鍵（正好符合漢語拼音與通用拼音），ㄘ則移到右下角的「-」鍵（等同於QWERTY鍵盤的「'」位置，正好與QWERTY倚天傳統的鍵位相同，並且也正好將ㄗㄘㄙ排在一起），ㄠ移到左下角的「;」鍵（這個符號在原本的倚天傳統鍵盤是ㄗ對應的符號），ㄥ與ㄦ移到右上角的「[」「]」的位置（與QWERTY倚天傳統的鍵位相同）

倚天26鍵：

維持原本的注音對應的英文鍵盤，但是聲調鍵移到上排的YFGC的位置（照「輕聲、二聲、三聲、四聲」的順序）（不應放在下排的JKBV等鍵位，因為下排最難碰到，但是聲調鍵除了一聲的字以外都會用到），因為這樣不會造成混淆（聲調可與聲母在同一鍵，但不可與介音或韻母在同一鍵，但是中排除了D鍵及S鍵以外均已有韻母佔據，儘管中排最容易碰到），ㄗ移到右下角的Z鍵（與Dvorak倚天傳統相同的鍵位），ㄠ則移到D鍵

許氏：

由於許氏鍵盤只有「手順」的注音與英文的鍵盤無關而是與注音的排列有關，而「手順」的注音包括所有聲調與ㄘㄛㄜ這三個注音，所以就照以下的連結來排列注音：

http://magicbetw.blogspot.com/2017/05/for-dvorak-layout.html

神通：

維持原本的注音對應的英文鍵盤，但是ㄓㄔㄕ這三個注音移到左上角的「'」「,」「.」的位置（等同於QWERTY鍵盤的QWE的位置），ㄦ移到右上角的「[」的位置（與QWERTY神通的鍵位相同）

星光：

由於是完全照漢語拼音排列而與注音的排列完全無關，所以完全維持原本的注音對應的英文鍵盤

另外你們支援的6種拼音輸入（漢語拼音、通用拼音、威妥瑪拼音、國音二式、耶魯拼音、華羅拼音）也可以開放用Dvorak鍵盤來輸入。

**Comment by ShikiSuen** [comment]
提建議之前，請先親自測試，否則只會帶來困擾、給他人以尋釁滋事之印象。

威注音輸入法的注音輸入模式都是做了 **KeyCode 強綁定**的，所以**無論鍵盤是 AZERTY 還是 DVORAK 都會自動映射為大千**（會在打注音時先自動翻譯為 QWERTY 再處理）。
拼音輸入模式的話，只需修改英數鍵盤佈局即可：
<img width="578" alt="image" src="https://user-images.githubusercontent.com/3164826/232979244-b7c7de68-60c2-4ef9-ae9f-260a7f9e84be.png">

P.S.: 今後，您每開一次工單、或每留言一次，都會被停權一個月（本次停權至 2023-05-20）。
該手段用來限制您發文的次數，以節省我這邊的應對壓力。

**Comment by ShikiSuen** [comment]
倚天傳統/倚天26鍵/許氏/神通/星光（等任何利用字母注音綁定的注音排列）與 Dvorak 等動態佈局的翻譯銜接支援確實尚未實裝。
但是，這個功能要不要做，我得先觀望一下。

**Comment by ShikiSuen** [comment]
暫無計畫引入魔幻小鱉的許氏優化方案。
原因： DvorakHsu 這十幾年來通行的版本都是新酷音輸入法內建的版本，該版本僅轉換基礎 ASCII Keyboard Mapping、而沒有採用魔幻小憋的許氏優化方案。

**Comment by xayahrainie4793** [comment]
你說你暫無計畫加入魔幻小鱉的許氏鍵盤優化方案，那有計畫加入我的倚天41鍵鍵盤跟倚天26鍵鍵盤的優化方案嗎？

**Comment by ShikiSuen** [comment]
@xayahrainie4793 也沒有。
