### ISSUE TITLE
[功能問題提報] 許氏注音按鍵配置有誤

### ISSUE THREAD

**Issue by CollieIsCute** [ShikiSuen/vChewing-CHS#426]
### **請在開新的工單之前閱讀《[故障提報與用儀器捉蟲](https://vchewing.github.io/BUGREPORT.html)》按照裡面的方法整理相關資訊、且在開工單之後電郵知會我。因各種可能原因，威注音的主程式師可能無法隨時收取 GitHub 與 Gitee 的工單提醒訊息。**

**摘要**

許氏注音按鍵配置有誤。

**快速分類**
請問您遇到的是：

- [ ] 輸入法崩潰或正在接受文字輸入的應用程式崩潰
- [x] 輸入法叫不出來，或無法正確敲出中文
- [ ] 無法切換至特定功能的啟用/停用狀態
- [ ] 輸入法效能有問題（執行速度太慢/電腦發燙）
- [ ] 輸入法應用程式介面顯示不正常（IMK 選字窗的應用介面美術瑕疵恕不受理，因為是 Apple 負責的）
- [ ] 輸入法亂放屁（請確保偏好設定內的廉恥模式的勾沒有被去掉）
- [ ] 其他

**問題發生步驟**
請問您是怎麼遇到這個問題的？像是：

我使用 3.4.7 的許氏注音， 'y' 和 'z' 鍵的功能被對調了。原本在 3.4.6 時 'y' 是 'ㄚ', 'z' 是 'ㄗ', 但在 3.4.7 會反過來變'ㄗ'和'ㄚ'。
剛剛試著從 github 下載 3.4.6 的 .app 檔安裝後一切恢復正常，因此我猜測是 3.4.7 版本的問題。

**預期正常狀況**

原本 'y' 在 3.4.6 是 'ㄚ', 'z' 是 'ㄗ'。

**電腦環境**
請問您在怎樣的環境遇到這個問題？

- 威注音版本：3.4.7
- 注音排列與基礎鍵盤佈局：許氏注音
- macOS 版本：13.3.1 (a)（22E772610a）
- 在哪個應用程式中打字遇到問題：brave 瀏覽器
- 電腦機種：macbook m2 air
- 其他特殊設備：qwerty 配列
- 特殊設定：從 3.4.6 升級至 3.4.7 時故障

**Comment by ShikiSuen** [comment]
請勿在下述位置將基礎鍵盤佈局設為「QWERTZ」，否則就會出現你說的錯誤。
<img width="578" alt="image" src="https://user-images.githubusercontent.com/3164826/236502973-3d351c58-09b4-4366-a7d6-48e472ed2fce.png">

許氏鍵盤的正確配置方法（QWERTY排列）：
<img width="569" alt="image" src="https://user-images.githubusercontent.com/3164826/236503186-1ef37f08-a2f6-4c96-acf9-62b5ac5fd530.png">

**Comment by ShikiSuen** [comment]
我另外請人幫忙測試一下許氏鍵盤好了。（我只會用大千傳統佈局。）

**Comment by CollieIsCute** [comment]
謝謝，原來是改到設定，現已修正。
