### ISSUE TITLE
我發現說明頁中有幾個地方有錯誤，然後我還有一些問題

### ISSUE THREAD

**Issue by xayahrainie4793** [ShikiSuen/vChewing-CHS#432]
1. https://vchewing.github.io/README.html#%E4%B8%BB%E8%A6%81%E7%89%B9%E8%89%B2%E5%8A%9F%E8%83%BD-feat 中有寫：「支援最多種類的拼音輸入（得帶有12345數字聲調）：漢語拼音、國音二式、耶魯拼音、華羅拼音、通用拼音。」，但是你們現在已經支援韋氏拼音了，不過頁面上卻沒有更新
2. https://vchewing.github.io/manual/arranges.html#%E6%98%9F%E5%85%89%E6%8E%92%E5%88%97-starlight 中的文字有誤：「與依照威妥瑪拼音習慣設計的許氏排列與倚天二十六鍵排列不同，星光排列更符合漢語拼音熟習者的思考方式」，但是只有倚天二十六鍵排列是照威妥瑪拼音（韋氏拼音）來排列的（ㄖ對應J，並且ㄍ不對應G、ㄗ不對應Z），許氏排列是照通用拼音（或國音二式）來排列的（ㄐ和ㄓ對應J、ㄖ對應R、ㄗ對應Z）
3. https://vchewing.github.io/manual/arranges.html#%E6%80%8E%E6%A8%A3%E5%8F%96%E6%8D%A8how-to-choose 中的「靈感來自『電丸科技 AK』的某期節目」的圖有問題，倚天忘形26鍵是動態注音排列，哪來快速並擊？例如你同時按下T鍵和M鍵，他會知道你要打的注音是ㄊㄢ還是ㄇㄤ嗎？此外「快速並擊」+「雙手分工」，不是只有大千注音符合，精業排列跟偽精業排列也一樣符合，至於倚天忘形26鍵跟許氏注音，則只符合「三列注音」這個條件而已
4. https://vchewing.github.io/manual/arranges.html ：「威注音僅推薦注音輸入法的初學者學習大千傳統佈局，因其左右手分工最為科學。」，但是見https://hackmd.io/@kccheng/BkfENF3FS ：「這是最重要的，要選擇倚天 26 鍵。除非是專業需要打字的人員，倚天26 是該文的作者推薦的最佳中文輸入法。」
5. https://github.com/vChewing/vChewing-macOS/blob/main/Packages/vChewing_Tekkon/Tests/TekkonTests/KeyTest_Hsu_A.swift 與https://github.com/vChewing/vChewing-macOS/blob/main/Packages/vChewing_Tekkon/Tests/TekkonTests/KeyTest_Starlight_A.swift 的程式碼建議修正，ㄍㄧㄠˊ和ㄍㄧㄣ這兩個讀音用除了倚天26鍵以外的任何鍵盤排列（包括許氏排列與星光排列）都可以正常輸入而不會造成衝突（倚天26鍵因為ㄍ和ㄑ在同一鍵，所以才無法輸入ㄍㄧㄠˊ和ㄍㄧㄣ這兩個讀音），就跟ㄎㄧㄤ這個讀音一樣
6. 見https://blog.xuite.net/crjpf/blog/7934419 ，這個頁面有一個新的鍵盤排列，是由政治大學中文系的劉又銘所設計的鍵盤，類似於星光排列，我暫且稱他為「劉氏鍵盤」，也叫做「擬音式注音鍵盤」，你們可以考慮加入這種鍵盤排列，還有見https://www.mobile01.com/topicdetail.php?f=511&t=6538385 中的2樓（IQuit）的回答的圖裡有一個「2025（零壹科技V2.2或1/1/86以前之版本）」的鍵盤排列，你們也可以考慮加入（他的回答的圖裡的七種鍵盤中的六種你們目前都已經有了，唯獨這一種還沒有），這樣再加上你們目前有的鍵盤排列，總共有12種鍵盤排列可供選擇
7.  見https://vchewing.github.io/manual/onboarding_ov.html ：「磁帶模式支援 CIN 與 CIN2 格式，可以用這種方式給威注音掛接一個字根輸入法來使用（比如五筆、快倉六、嘸蝦米，等）」。所以你們的磁帶模式有沒有支援這些輸入法？[倉頡輸入法](https://zh.wikipedia.org/wiki/%E5%80%89%E9%A0%A1%E8%BC%B8%E5%85%A5%E6%B3%95)、[速成輸入法](https://zh.wikipedia.org/wiki/%E9%80%9F%E6%88%90%E8%BC%B8%E5%85%A5%E6%B3%95)、[快速倉頡輸入法](https://zh.wikipedia.org/wiki/%E5%BF%AB%E9%80%9F%E5%80%89%E9%A0%A1%E8%BC%B8%E5%85%A5%E6%B3%95)、[全方位倉頡輸入法](https://zh.wikipedia.org/wiki/%E5%85%A8%E6%96%B9%E4%BD%8D%E5%80%89%E9%A0%A1%E8%BC%B8%E5%85%A5%E6%B3%95)、[大易輸入法](https://zh.wikipedia.org/wiki/%E5%A4%A7%E6%98%93%E8%BC%B8%E5%85%A5%E6%B3%95)、[行列輸入法](https://zh.wikipedia.org/wiki/%E8%A1%8C%E5%88%97%E8%BE%93%E5%85%A5%E6%B3%95)、[嘸蝦米輸入法](https://zh.wikipedia.org/wiki/%E5%98%B8%E8%9D%A6%E7%B1%B3%E8%BC%B8%E5%85%A5%E6%B3%95)、[輕鬆輸入法](http://eshensh.net/ez/index5.html)、[五筆字型輸入法](https://zh.wikipedia.org/wiki/%E4%BA%94%E7%AC%94%E5%AD%97%E5%9E%8B%E8%BE%93%E5%85%A5%E6%B3%95)、[徐碼輸入法](https://zh.wikiversity.org/zh-hant/%E5%BE%90%E6%B0%8F%E5%AD%97%E5%BD%A2%E8%BC%B8%E5%85%A5%E6%B3%95)、[鄭碼輸入法](https://zh.wikipedia.org/wiki/%E9%83%91%E7%A0%81)、[表形碼輸入法](https://zh.wikipedia.org/wiki/%E8%A1%A8%E5%BD%A2%E7%A0%81)、[九方輸入法](https://zh.wikipedia.org/wiki/%E4%B9%9D%E6%96%B9%E8%BC%B8%E5%85%A5%E6%B3%95)、[二筆輸入法](https://zh.wikipedia.org/wiki/%E4%BA%8C%E7%AC%94%E8%BE%93%E5%85%A5%E6%B3%95)？或者「無理碼」的輸入法如[Big5碼輸入法](https://zh.wikipedia.org/wiki/%E5%A4%A7%E4%BA%94%E7%A2%BC)、[GB2312碼輸入法](https://zh.wikipedia.org/wiki/GB_2312) 、[Unicode碼輸入法](https://zh.wikipedia.org/wiki/Unicode)、[中文電碼輸入法](https://zh.wikipedia.org/wiki/%E4%B8%AD%E6%96%87%E7%94%B5%E7%A0%81)？還有[雙拼輸入法](https://zh.wikipedia.org/wiki/%E5%8F%8C%E6%8B%BC)也有在你們磁帶模式的支援範圍內嗎？
8. 見https://github.com/vChewing/vChewing-macOS/issues/357 ，「得擇日審視每個讀音下的候選字（單個漢字）的優先順序」，請問你們的輸出字元集是Big5碼（繁體中文）與GB2312碼（簡體中文）還是Unicode？如果是Unicode，有沒有包括擴充A區到F區的字元以及香港增部符集字元？我建議候選字（單個漢字）的優先順序可以是（繁體中文）：Big5碼第一字面（常用字5401字）->Big5碼第二字面（非常用字7652字）->Unicode有收但Big5碼沒有收的字->Unicode擴充A區->Unicode擴充B區->香港增部符集字元->Unicode擴充C區->Unicode擴充D區->Unicode擴充E區->Unicode擴充F區，如果是簡體中文，則為：GB2312碼第一字面（常用字3755字）->GB2312碼第二字面（非常用字3008字）->Unicode有收但GB2312碼沒有收的字->後面相同，另外在「Big5碼第一字面（常用字5401字）」、「Big5碼第二字面（非常用字7652字）」、「GB2312碼第一字面（常用字3755字）」、「GB2312碼第二字面（非常用字3008字）」當中，則可以分別按照[繁體中文漢字字頻總表](https://pair.nknu.edu.tw/literacy/UploadFile/News/201712291806/%E6%95%99%E8%82%B2%E9%83%A8%E5%AD%97%E5%BA%AB5021%E5%AD%97.pdf)與[簡體中文漢字字頻總表](https://wenku.baidu.com/view/09281b0433d4b14e84246872.html)來排序

**Comment by ShikiSuen** [comment]
@xayahrainie4793 
我能 Google 到的與「零壹 202S」有關的內容都稱其與大千排列雷同。
除非你能找到「零壹 202S」實體鍵盤照片證明其與大千的不同，否則這個鍵盤我沒法實作。
<img width="653" alt="image" src="https://github.com/vChewing/vChewing-macOS/assets/3164826/dff4464a-2fc2-44d8-9e3a-6474932f014b">

**Comment by ShikiSuen** [comment]
- [x] 1. 回頭會抽空更新使用手冊；
- [x] 2. 回頭會抽空更新使用手冊；
- [x] 3. 回頭會抽空更新使用手冊；
- [x] 4. 他的觀點我完全不同意，故不會因為這一條而對使用手冊做修改；
- [x] 5. 接下來僅會對 CSharp 與 Swift 版 Tekkon 引擎做這個修正，我實在沒那個生命繼續浪費在 C++ 上面；
- [x] 6. 這個有在檢討，但不一定做。然而，因為發現了越來越多的人對注音鍵盤排列的自訂需求，所以竊以為更好的解決方法是：業界內得有人設計出「有具備這種自訂功能」的注拼引擎。不然，尤其是動態注音排列，每寫一套冷門的，都得制定縝密的邏輯判定規則，還沒有人給我付工錢。另外，我能 Google 到的與「零壹 202S」有關的內容都稱其與大千排列雷同，且「零壹 2025」找不到相關的圖片。除非你能找到它的實體鍵盤照片證明其與大千的不同，否則這個鍵盤我沒法實作。
<img width="653" alt="image" src="https://github.com/vChewing/vChewing-macOS/assets/3164826/dff4464a-2fc2-44d8-9e3a-6474932f014b">

- [x] 7. 理論上來講，只要是 CIN / CIN2 支援，就能用。實際情況雖恐得親自測試，但不屬於威注音的保障範圍內（MIT 開源的專案，能保障什麼？）。
- [x] 8. 你只要開啟全字庫模式，就可以輸入全字庫模式所支援的漢字。

**Comment by ShikiSuen** [comment]
第五點補遺：這兩個讀音無法通過單元測試，看來恐怕得追加判定：
<img width="1185" alt="image" src="https://github.com/vChewing/vChewing-macOS/assets/3164826/28fe2f4e-ecd2-45e4-88a1-935d89b3998a">
<img width="1173" alt="image" src="https://github.com/vChewing/vChewing-macOS/assets/3164826/04628323-9556-47b3-b6c3-4a7801684136">

**Comment by ShikiSuen** [comment]
網站的內容根據 1-3 做了訂正。

關於第6條：
- 我給劉教授寫電郵詢問他這注音排列在台灣大概多少人在用，等他回信。沒回信的話，我不做這套排列的支援；有回信的話，根據他的答覆內容，我再繼續判斷是否研究對這套注音排列的支援的實作。
- 與零壹 2025 注音排列有關的資訊，我已經給零壹科技臉書傳私訊了，看他們怎麼回應。

**Comment by xayahrainie4793** [comment]
還有你們也可以考慮加入這個許氏鍵盤的連結到主頁面中許氏鍵盤的段落https://vchewing.github.io/manual/arranges.html#%E8%A8%B1%E6%B0%8F%E5%9C%8B%E9%9F%B3%E8%87%AA%E7%84%B6%E6%8E%92%E5%88%97-hsu ，或者直接複製這個連結中的「D-2 、「許氏鍵盤」對應說明」段落中的內容到主頁面中許氏鍵盤的段落：

https://web.archive.org/web/20070214130835/http://www.iis.sinica.edu.tw/IASL/products/going5/chap-ad.html

**Comment by xayahrainie4793** [comment]
你們可以在主頁面的星光排列的段落中https://vchewing.github.io/manual/arranges.html#%E6%98%9F%E5%85%89%E6%8E%92%E5%88%97-starlight 詳盡說明「倚天二十六鍵排列是照威妥瑪拼音（韋氏拼音）來排列，許氏排列是照通用拼音或國音二式來排列，星光排列是照漢語拼音來排列」

**Comment by xayahrainie4793** [comment]
程式碼有錯，許氏鍵盤的ㄍㄧㄠˊ並不是vezf，而是gewd，你應該是直接用倚天26鍵的程式碼複製過去，卻忘了改

**Comment by xayahrainie4793** [comment]
第8點，你不是在#357說「目前的資料庫在這方面偶爾會有違反常識的結果」嗎？所以我就建議按照這種方式排列每個讀音下的候選字（單個漢字）的優先順序

**Comment by xayahrainie4793** [comment]
那個「靈感來自『電丸科技 AK』的某期節目」的圖：

「快速並擊」+「雙手分工」：應包含「大千注音」、「精業注音」、「偽精業注音」
「快速並擊」+「三列注音」：應包含「倚天26鍵注音」、「許氏注音」、「星光注音」（星光注音是否為「三列注音」可能有爭議，因為聲調鍵是在數字鍵上），以及https://blog.xuite.net/crjpf/blog/7934419 中的「劉氏注音」（擬音式注音）
「雙手分工」+「三列注音」：包含「大千26鍵注音」（你們的圖在這部分是對的）

另外，「倚天注音」、「神通注音」、「IBM注音」則僅有「快速並擊」而已

**Comment by ShikiSuen** [comment]
@xayahrainie4793 
停權七個月（共計七條回覆）。
沒有人活該為你做任何事情。

**Comment by ShikiSuen** [comment]
<img width="388" alt="圖片" src="https://github.com/vChewing/vChewing-macOS/assets/3164826/4ca0b108-0f71-4ec3-9983-cbac14fa9bf1">

靠，沒有七個月的選項，那就30天吧。

**Comment by ShikiSuen** [comment]
真的很抱歉，實在受不了了。

**Comment by ShikiSuen** [comment]
> 程式碼有錯，許氏鍵盤的ㄍㄧㄠˊ並不是vezf，而是gewd，你應該是直接用倚天26鍵的程式碼複製過去，卻忘了改

那也沒見你改出來測試可用性啊？
<img width="1158" alt="圖片" src="https://github.com/vChewing/vChewing-macOS/assets/3164826/ced9a124-69a8-4204-95bd-c8f2b92ae4bc">

**Comment by ShikiSuen** [comment]
看來是 Tekkon 的邏輯處理出了問題：將本該限定於倚天忘形排列的某道處理強加到其他排列上了。
正好可以併入威注音 3.4.8 修正。
<img width="1224" alt="圖片" src="https://github.com/vChewing/vChewing-macOS/assets/3164826/bb92a6d4-13ff-4c6c-81dc-3785c6393d1d">

**Comment by ShikiSuen** [comment]
還是關掉這個工單好了，根據具體的問題拆出新的工單來管理。

**Comment by ShikiSuen** [comment]
第八點算了，這個問題現在已經幾乎感覺不到了。威注音輸入法的詞庫的詞頻每次都在手動調整。

**Comment by ShikiSuen** [comment]
> 那個「靈感來自『電丸科技 AK』的某期節目」的圖：
> 
> 「快速並擊」+「雙手分工」：應包含「大千注音」、「精業注音」、「偽精業注音」 「快速並擊」+「三列注音」：應包含「倚天26鍵注音」、「許氏注音」、「星光注音」（星光注音是否為「三列注音」可能有爭議，因為聲調鍵是在數字鍵上），以及https://blog.xuite.net/crjpf/blog/7934419 中的「劉氏注音」（擬音式注音） 「雙手分工」+「三列注音」：包含「大千26鍵注音」（你們的圖在這部分是對的）
> 
> 另外，「倚天注音」、「神通注音」、「IBM注音」則僅有「快速並擊」而已

在劉教授電郵回應之前，我不會考慮任何與劉氏注音有關的內容補充。

鐵恨注拼引擎對複合注音鍵盤佈局（倚天26、許氏、星光、酷音大千26）是**有並擊支援**的，**除非相關的按鍵組合有歧義**。
**沒有誰規定**說這種複合注音鍵盤佈局「該不該有」並擊支援。

**Comment by ShikiSuen** [comment]
補記：今天與零壹科技通過電話了。當初零壹科技確實一開始有在使用另外的注音排列。然而，對方有提及當時的各大中文電腦廠商在注音鍵盤排列這方面的百家爭鳴的時代特徵。這樣來看，零壹 2025 的注音排列恐無繼續支援之必要價值。連 Google 其鍵盤排列照片都已再無可能了。比起這個，擁有一套可以自訂注音鍵盤排列的次世代注拼引擎，更重要。
