### ISSUE TITLE
[功能問題提報]其他問題

### ISSUE THREAD

**Issue by xayahrainie4793** [ShikiSuen/vChewing-CHS#453]
1. [https://vchewing.github.io/manual/arranges.html](url) 中有提到「1.8.5 版（及在此之前版本的）威注音輸入法不支援星光排列」，請再寫上「3.4.6 版（及在此之前版本的）威注音輸入法不支援劉氏排列」
2. 在工單[https://github.com/vChewing/vChewing-macOS/issues/434](url)上你的說法有點問題：「因為ㄘㄝ共鍵，且兩個都可以單獨當作漢字讀音，所以無法實作。」，但是倚天26鍵鍵盤也是ㄘㄝ共鍵（都在W鍵）以及ㄗㄟ共鍵（都在Q鍵）啊（這四個注音都可以單獨當作漢字讀音），許氏鍵盤則是ㄧㄝ共鍵（都在E鍵）與ㄘㄟ共鍵（都在A鍵）與ㄥㄦ共鍵（都在L鍵）（這六個注音都可以單獨當作漢字讀音），此外劉氏鍵盤原本的版本也是ㄜㄝ共鍵（跟星光鍵盤一樣），且兩個都可以單獨當作漢字讀音，所以沒有什麼不能實作，只是ㄝ、ㄟ、ㄥ單獨使用的字會打不出來，不過這些字都很少見（誒、欸、鞥），打不出來應該沒有關係（？
3. 劉氏注音你在[https://github.com/vChewing/vChewing-macOS/issues/434](url)說遷就微軟新注音的鍵盤自訂功能時，要把ㄝ改設在C鍵，但是[https://blog.xuite.net/crjpf/blog/7934419](url)卻說遷就微軟新注音的鍵盤自訂功能時，要把ㄝ改設在I鍵（跟ㄧ共鍵，跟許氏鍵盤類似）或者改設在K鍵。
4. ［建議，只是建議而已，你可以不用照做］，建議把劉教授的原始設計方案（ㄝ在E鍵，ㄦ在L鍵）稱作「劉氏鍵盤」，遷就微軟新注音的鍵盤自訂功能的版本（ㄝ在C鍵或I鍵或K鍵，ㄦ在T鍵）則稱作「偽劉氏鍵盤」，分為兩種不同的鍵盤，就跟「精業鍵盤」和「偽精業鍵盤」類似，這樣就總共有12種注音鍵盤排列可以使用
5. 鐵恨引擎在這方面應該要修改：複音切換不應該把某個鍵的注音轉成該鍵根本沒有對應到的注音，例如你對於動態的注音鍵盤，ㄑㄨ都會自動轉成ㄍㄨ，而ㄍㄧ和ㄍㄩ也都會分別轉成ㄑㄧ和ㄑㄩ，但是這應該只能適用於倚天26鍵鍵盤，許氏鍵盤和星光鍵盤的ㄍ和ㄑ又沒有共鍵，這種自動轉換完全錯誤，例如你在許氏鍵盤的環境下按下GU（ㄍㄩ）而自動轉成ㄑㄩ，不過許氏鍵盤的G鍵又沒有ㄑ這個注音，其他依此類推，倚天26鍵鍵盤也不應該把ㄔㄧ和ㄔㄩ轉成ㄑㄧ和ㄑㄩ，因為倚天26鍵鍵盤的Y鍵只有ㄔ一個注音，沒有ㄑ這個注音

**Comment by xayahrainie4793** [comment]
另外也請檢驗你們是否有包含這些讀音（這些是較少使用的讀音）：

1. ㄍㄚ（嘎）
2. ㄛ（哦）
3. ㄌㄛ（咯）
4. ㄇㄜ（麼）
5. ㄝ（誒）
6. ㄟ（欸）
7. ㄉㄟ（得）
8. ㄊㄟ（忒）
9. ㄎㄟ（剋）
10. ㄓㄟ（這）
11. ㄘㄟ（𤭢）
12. ㄙㄟ（塞）
13. ㄆㄡ（剖）
14. ㄋㄡ（耨）
15. ㄉㄣ（扽）
16. ㄌㄣ（啉）
17. ㄗㄣ（簪）
18. ㄘㄣ（岑）
19. ㄥ（鞥）
20. ㄕㄨㄥ（蚣）
21. ㄆㄧㄚ（啪）
22. ㄉㄧㄚ（嗲）
23. ㄋㄧㄚ（㖸）
24. ㄌㄧㄚ（倆）
25. ㄧㄛ（唷）
26. ㄧㄞ（崖）
27. ㄈㄧㄠ（𧟰）
28. ㄍㄧㄠ（譙）
29. ㄇㄧㄡ（謬）
30. ㄎㄧㄡ（Q）
31. ㄉㄧㄣ（𨈖）
32. ㄍㄧㄣ（囝）
33. ㄅㄧㄤ（𰻞）
34. ㄉㄧㄤ（噹）
35. ㄎㄧㄤ（鏘）
36. ㄐㄩㄥ（窘）
37. ㄔㄨㄚ（欻）
38. ㄖㄨㄚ（挼）
39. ㄓㄨㄞ（拽）
40. ㄔㄨㄞ（揣）
41. ㄋㄨㄟ（捼）
42. ㄋㄨㄣ（黁）
43. ㄉㄨㄤ（成龍）
44. ㄌㄩㄢ（孿）
45. ㄌㄩㄣ（淋）
46. ㄑ（啐）

**Comment by ShikiSuen** [comment]
1. 已經補上「3.4.6 版（及在此之前版本的）威注音輸入法不支援劉氏排列」。
2. 工單備忘錄的內容無法反應輸入法目前最新的情況。實際情況是：目前的威注音輸入法的劉氏注音排列支援**有同時支援「劉氏注音理想排列」與「微軟新注音相容排列」，沒有分開的必要。這是我與劉教授親自討論過的，他有意見的話肯定早就跟我講過了**。
3. 你那 xuite 的文章舊了。劉教授後來又有改過微軟新注音相容修改方法，且私下給我看過（見下圖）。**論及對於劉氏注音鍵盤的方案的實作，我只可能對劉教授負責，而不可能對你負責。今後任何由你發起的與劉氏注音排列有關的任何「建議」均不會被睬理。**
![image](https://github.com/vChewing/vChewing-macOS/assets/3164826/931ea446-da53-4cfd-b5da-f13af4501cdd)
4. 參見上文「2.」的說明。
5. 請自行雇用其他程式師幫你打造你想要的理想的注拼引擎、而不是在這裡來亂。我不認為目前的鐵恨注拼引擎在幾種動態注音排列的處理過程當中共用防呆設計有什麼不妥。
6. 你這次對漢字讀音的收錄提議我不打算理睬，因為裡面出現了威注音輸入法目前已經收錄的漢字讀音、這使得我又要付出額外的時間精力成本來確認哪些讀音是否有收錄。如果連開了全字庫模式都沒有收的話，你得使用輸入法本身的注音反查功能。
