### ISSUE TITLE
[功能問題提報] 在 Discord 按下 RShift 時偶爾會觸發兩次

### ISSUE THREAD

**Issue by pan93412** [ShikiSuen/vChewing-CHS#460]
### **請在開新的工單之前閱讀《[故障提報與用儀器捉蟲](https://vchewing.github.io/BUGREPORT.html)》按照裡面的方法整理相關資訊、且在開工單之後電郵知會我。因各種可能原因，威注音的主程式師可能無法隨時收取 GitHub 與 Gitee 的工單提醒訊息。**

**摘要**

在 Discord 按下右 Shift 時，會重複彈跳兩次中英切換飄窗。重新啟動 Discord 可解決症狀；其他應用程式不會發生類似問題。

**快速分類**
請問您遇到的是：

- [ ] 輸入法崩潰或正在接受文字輸入的應用程式崩潰
- [ ] 輸入法叫不出來，或無法正確敲出中文
- [x] 無法切換至特定功能的啟用/停用狀態
- [ ] 輸入法效能有問題（執行速度太慢/電腦發燙）
- [ ] 輸入法應用程式介面顯示不正常（IMK 選字窗的應用介面美術瑕疵恕不受理，因為是 Apple 負責的）
- [ ] 輸入法亂放屁（請確保偏好設定內的廉恥模式的勾沒有被去掉）
- [ ] 其他

**問題發生步驟**

1. 開啟 Discord 然後 focus 在輸出框
2. 敲下一次 Shift，KeyCastr 可觀查到只敲下一次，但飄窗可能會快速重複兩次
3. 切回其他應用程式（如 Messenger）再重新敲一次 Shift
4. 這次只切換一次

**預期正常狀況**

我預期所有應用程式下，按一次 Shift 對應一次切換。

**螢幕截圖或螢幕錄製**

https://github.com/vChewing/vChewing-macOS/assets/28441561/0c49acc9-8e9a-46cc-a5c8-0db04ff74e0e

**電腦環境**
請問您在怎樣的環境遇到這個問題？

- 威注音版本：3.5.1 (Build 3501)
- 注音排列與基礎鍵盤佈局：大千排列、Apple 標準注音鍵盤佈局
- macOS 版本：macOS 13.4.1 (22F82)
- 在哪個應用程式中打字遇到問題：Discord PTB 209361 (c4fae92), with BetterDiscord v1.9.3
- 電腦機種：Apple Sillion CPU
- 其他特殊設備：無
- 特殊設定：無

**Comment by ShikiSuen** [comment]
我暫時認定這是 Discord 特有問題。但恐需他人協助測試調查**該問題是從最早哪一版威注音開始出現的**。

**Comment by ShikiSuen** [comment]
Closing this issue since the issuer reported that the problem disappeared after rebooting Discord.
