### ISSUE TITLE
[功能问题提报]无法在word中选择并使用威注音

### ISSUE THREAD

**Issue by webstorm-dxy** [ShikiSuen/vChewing-CHS#477]
### **请在开新的工单之前阅读《[故障提报与用仪器捉虫](https://vchewing.github.io/BUGREPORT.html)》按照里面的方法整理相关资讯、且在开工单之后电邮知会我。因各种可能原因，威注音的主程式师可能无法随时收取 GitHub 与 Gitee 的工单提醒讯息。**

**摘要**
请简单说明您遇到了什么问题。这份表格虽然是中文的（我们相信注音输入法的用户应该都能看懂中文），但开发团队可以使用中英文沟通，您也可以使用英文提报问题。

**快速分类**
请问您遇到的是：

- [x] 输入法叫不出来，或无法正确敲出中文

**问题发生步骤**
请问您是怎么遇到这个问题的？像是：

> 打开word打字，无法切换到威注音

**预期正常状况**
您觉得这是不正常的状况，那您觉得正常结果应该是…？

> 能够正常切换

**荧幕截图或荧幕录制**
<img width="220" alt="image" src="https://github.com/vChewing/vChewing-macOS/assets/85004777/b7b03e1c-7696-4345-bfef-c9df721431bd">

https://github.com/vChewing/vChewing-macOS/assets/85004777/5b7af3c4-53f1-4c2f-bb69-8be3ba1e21d7

**电脑环境**
Mac OS 13

- 威注音版本：Build 3502
- 注音排列与基础键盘布局：神通
- macOS 版本：macoS Ventura beta 13.5 (22G5059d)
- 在哪个应用程式中打字遇到问题：MS 365 Word
- 电脑机种：Apple Silicon CPU
- 其他特殊设备：无
- 特殊设定：无

**Comment by ShikiSuen** [comment]
请在重新开机之后拿威注音 3.5.3 版重新测试确认是否仍有该故障。

**Comment by ShikiSuen** [comment]
我这边没测试 3.5.2，测试了 3.5.3 版发现一切正常。
可能真的跟 3.5.2 版用 `Set<NSEvent>` 时出现的故障有关（3.5.3 改用 Array 来临时登记近期处理过的 NSEvent）。

<img width="732" alt="image" src="https://github.com/vChewing/vChewing-macOS/assets/3164826/f5381eda-ae3a-4da1-b593-b7e5fb3d2caf">

**Comment by ShikiSuen** [comment]
@webstorm-dxy 请问您是否有在使用诸如 1password / BitWarden 之类的密码管理 App？
如果是的話，请问这些 App 的版本是？

**Comment by ShikiSuen** [comment]
该工单暂时关闭、且假定 3.6.1 版能够应对这种情况。如果该故障仍旧存在的话，请再留言。
