### ISSUE TITLE
[功能建議]希望cin2可以支持五笔的多字词组输入

### ISSUE THREAD

**Issue by webstorm-dxy** [ShikiSuen/vChewing-CHS#479]
**免責聲明**

威注音輸入法保留拒絕任何種類的功能建議的權利（本來就有）。

閱讀來自各位使用者的功能建議請求，是一回事；**但**威注音研發方怎樣利用這些建議請求背後的潛在資訊、來制定威注音接下來的研發方向（或可能棄用相關想法），則是**另一回事**。

**痛點**
五笔的词库中有很多的词组，而我在导入五笔86版的词库在cin磁带中之后无法输入字符，希望可以添加这方面的支持
**功能說明**
能够使用五笔86版的cin词库，可以实现词组的输入

**替代方案**
五笔cin词库的单字输入

**其他**
联网词库，像其他的中文输入法一样，虽然是离线词库，但是已经能够比较流畅的输入中文了，希望可以变的更加的智能

**Comment by ShikiSuen** [comment]
您可以试试将与词组有关的内容塞到使用者辞典当中？

至于联网词库，这个功能我不太会实装，而且像是那种「专门的五笔输入法」才会去支持的功能。如果真要实作的话，我建议在像诸如业火五笔（ https://github.com/qwertyyb/Fire ）这样的专门的五笔输入法内实作。
