### ISSUE TITLE
[功能問題提報] 的確是切到威注音但某幾個 APP 不管打都只能打出英文，只能重啟

### ISSUE THREAD

**Issue by Charming0420** [ShikiSuen/vChewing-CHS#483]
請問您遇到的是：

- [ ] 輸入法崩潰或正在接受文字輸入的應用程式崩潰
- [x] 輸入法叫不出來，或無法正確敲出中文
- [ ] 無法切換至特定功能的啟用/停用狀態
- [ ] 輸入法效能有問題（執行速度太慢/電腦發燙）
- [ ] 輸入法應用程式介面顯示不正常（IMK 選字窗的應用介面美術瑕疵恕不受理，因為是 Apple 負責的）
- [ ] 輸入法亂放屁（請確保偏好設定內的廉恥模式的勾沒有被去掉）
- [ ] 其他

**問題發生步驟**
請問您是怎麼遇到這個問題的？

簡單來說就是切到威注音 但有的 APP 不管怎樣都打不出中文 只會打出英文
我也沒有做什麼，有時候可能是有按到 Control、Command、Option 之類的按鍵
目前發生情況的地方：Line、Discord（都已經加入客體應用列表中）
而我唯一能解決的方法是從選項中重啟威注音

**預期正常狀況**
您覺得這是不正常的狀況，那您覺得正常結果應該是…？

不該

**電腦環境**
請問您在怎樣的環境遇到這個問題？

- 威注音版本：3.5.4
- 注音排列與基礎鍵盤佈局：大千排列，Apple 標準注音鍵盤佈局（大千）
- macOS 版本：13.2.1（22D68）
- 在哪個應用程式中打字遇到問題：Line v8.2.0 / Discord 0.0.277
- 電腦機種：Macbook Pro M2 2023 14"
- 其他特殊設備：雙螢幕使用
- 特殊設定：無

**其他**
其他你覺得問題發生的疑點，或其他你想跟威注音開發團隊說的話。

**Comment by ShikiSuen** [comment]
先問兩個問題：

一、請問除了 Line、Discord 以外還有別的軟體也這樣嗎？
二、請問威注音 3.5.3 版是否有這個故障？也就是說我想知道這些故障是從哪一版本開始的。

您可以臨時先用 SwiftCord 湊合一陣子：https://github.com/SwiftcordApp/Swiftcord ，比 Discord 官方 App 對 macOS 相容性更優。

因為你不是第一個提報 LINE 當中的這個問題的人，且你提報的這個問題也牽涉到 Discord、且利用客體管理器也無法繞開這類故障，所以我決定重新審視一下近幾個版本的程式碼改動。下文留作我個人備忘用：

> 從選項中重啟威注音

既然樓主能這樣做，證明輸入法 Session 有建構成功。（不然的話，連輸入法選單都不能正常顯示。）

**Comment by ShikiSuen** [comment]
@Charming0420 另外，請依照這篇文章的指引生成 IPS 檔案、且將 IPS 檔案 ZIP 壓縮之後貼到這個討論串內。
https://vchewing.github.io/BUGREPORT.html
雖然截至 3.5.4 版為止的 IPS 報告我無法完全解讀（因為我手頭沒有各自對應的 dSYM 檔案），但多少還能看到一些有用資訊。

**Comment by Charming0420** [comment]
> 先問兩個問題：
> 
> 一、請問除了 Line、Discord 以外還有別的軟體也這樣嗎？ 二、請問威注音 3.5.3 版是否有這個故障？也就是說我想知道這些故障是從哪一版本開始的。
> 
> 您可以臨時先用 SwiftCord 湊合一陣子：https://github.com/SwiftcordApp/Swiftcord ，比 Discord 官方 App 對 macOS 相容性更優。
> 
> 因為你不是第一個提報 LINE 當中的這個問題的人，且你提報的這個問題也牽涉到 Discord、且利用客體管理器也無法繞開這類故障，所以我決定重新審視一下近幾個版本的程式碼改動。下文留作我個人備忘用：
> 
> > 從選項中重啟威注音
> 
> 既然樓主能這樣做，證明輸入法 Session 有建構成功。（不然的話，連輸入法選單都不能正常顯示。）

1. 剛剛又意外觸發了 Notion，也是同樣狀況，這次我錄影下來了，以下提供給您參考
🔗 : https://youtube.com/shorts/4XBp0z1IAnc?feature=share

2. 這個我無法確定，因為我是今天第一天開始使用威注音的用戶

**Comment by Charming0420** [comment]
> @Charming0420 另外，請依照這篇文章的指引生成 IPS 檔案、且將 IPS 檔案 ZIP 壓縮之後貼到這個討論串內。 https://vchewing.github.io/BUGREPORT.html 雖然截至 3.5.4 版為止的 IPS 報告我無法完全解讀（因為我手頭沒有各自對應的 dSYM 檔案），但多少還能看到一些有用資訊。

至於 IPS，我嘗試找過了，並沒有發現裡面有 vChewing 的文件，感謝您！

**Comment by ShikiSuen** [comment]
@Charming0420 Notion 的故障我無法重現。
我的電腦是 2018 mac mini 且系統是 macOS 14 Sonoma 首發正式版。用來測試的是威注音 3.8.4 正式版。
我這邊的操作錄影在此：

https://github.com/vChewing/vChewing-macOS/assets/3164826/3cdd3fcf-c09a-4904-9c6a-968e394494e4

**Comment by ShikiSuen** [comment]
目前的問題難點在於：任何與 LINE / Discord 官方客戶端 / Notion 筆記有關的故障提報在我這邊都無法重現。
我看看要不要再新增一些額外的相容性處理。

**Comment by ShikiSuen** [comment]
請問您方便將您的 imessage 聯絡方式傳給「上文記載的 BUGREPORT 網址當中顯示的以 yeah.net 結尾的電郵」嗎？
我可能最近會洗一個測試版本找您私下測試一下問題是否解決。

**Comment by Charming0420** [comment]
> @Charming0420 Notion 的故障我無法重現。 我的電腦是 2018 mac mini 且系統是 macOS 14 Sonoma 首發正式版。用來測試的是威注音 3.8.4 正式版。 我這邊的操作錄影在此：
> 
>  2023-09-13.21.10.45.mov

我平常使用時也沒有問題，也就是重新啟動後都是可以正常使用
都是經過一些時間，可能我有按到、誤觸什麼按鍵導致這個 Bug 產生的
另外，聯繫方式已經由 email 發送給您，再次感謝您！

**Comment by ShikiSuen** [comment]
@Charming0420 那個電郵是 `shikisuen◉yeah●net`，我目前尚未收到您的電郵。

**Comment by Charming0420** [comment]
> @Charming0420 那個電郵是 `shikisuen◉yeah●net`，我目前尚未收到您的電郵。
![截圖 2023-09-13 下午10 43 19](https://github.com/vChewing/vChewing-macOS/assets/72650268/b66d16a7-cbca-44dc-833c-ebe8ceab47a8)
被你的信箱退件了 哈哈 我該怎麼做呢

**Comment by ShikiSuen** [comment]
@Charming0420 我有收到您第一封電郵。

這週之內我會抽時間電郵給您測試版的安裝程式。（目前 notarization 無法順利進行，跟 Apple 聯絡這個問題需要一些時間。）

**Comment by ShikiSuen** [comment]
@Charming0420 測試版已經送出。

**Comment by ShikiSuen** [comment]
備忘：樓主已經開始在用這次的測試版。從現在開始進入 48 小時觀察期。
期間內沒有再遇到故障的話，則該工單關閉、視為已完成。

**Comment by ShikiSuen** [comment]
問題查明：
備忘：樓主發現故障觸發的熱鍵是 `Shift+↓`。
這證明該故障的觸發位置在 ShiftKeyUpChecker。
也就是說，ShiftKeyUpChecker 需要對上下文兩組訊號進行更嚴格的 KeyCode 一致性檢查。

威注音這邊已經在 bleed 分支修了這個故障，回頭會再洗測試版給樓主與 @pan93412 同時測試。
之後我會給業火五筆輸入法也推送 PR 補上這個缺失的判斷條件。

**Comment by ShikiSuen** [comment]
暫時先結案。

**Comment by amowu** [comment]
請問這個修復已經發布了嗎？我是 macOS Sonoma 第一次安裝威注音 3.8.4，目前在 VS Code 跟 Arc Browser 都遇到突然不能輸入中文的問題。

**Comment by ShikiSuen** [comment]
@amowu 這種情況下請將電腦靜置一分鐘。如果有 SecureEventInput 濫用狀態警告的話，看警告裡面提到哪個程式出故障，然後找這個程式的開發商算帳。威注音不替那些濫用 SecureEventInput（用完忘記及時關掉）的 App 擦屁股。

（macOS 第三方輸入法這十幾年來都飽受這類敗類 App 的荼毒。）

**Comment by amowu** [comment]
> @amowu 這種情況下請將電腦靜置一分鐘。如果有 SecureEventInput 濫用狀態警告的話，看警告裡面提到哪個程式出故障，然後找這個程式的開發商算帳。威注音不替那些濫用 SecureEventInput（用完忘記及時關掉）的 App 擦屁股。
> 
> （macOS 第三方輸入法這十幾年來都飽受這類敗類 App 的荼毒。）

恩...我試著擺了一陣子，沒有跳警告耶，不果還是感謝回覆啦，我再試用一陣子看看

**Comment by ShikiSuen** [comment]
@amowu 我沒在用 Arc Browser，不過我在 VSCode 確實沒有遇到您講過的問題。
只是我也沒有在 VSCode 遇到過需要輸入密碼的情況就是了。
