### ISSUE TITLE
[功能建議]是否能提供選項，關閉當 Capslock 亮燈時改為英文小寫輸入

### ISSUE THREAD

**Issue by a0972199950** [ShikiSuen/vChewing-CHS#492]
**痛點**

由於威注音不像微軟中文輸入法那樣，以圖標顯示當前是中文輸入還是英文輸入，只會在切換時跳出一個小通知。這特性會造成無法再輸入前就知道是中文還是英文。因此我利用其他軟體(karabiner-elements)達成用左邊 shift 切換輸入法的功能，藉此可以明確知道當前輸入法是什麼

而在實際的打字情境，時常發生以左 shift 切換成英文後，利用 Capslock 輸入大寫字母，之後再用左 shift 切換回中文輸入。這個情境下，切換回威注音時，Capslock 的燈還是亮著的，很容易會誤輸入成英文，或是以為自己沒有成功切換輸入法。所以希望可以提供一個選項，移除 Capslock 亮燈時以英文小寫輸入的功能

**功能說明**

在設定中提供一個選項，讓威注音不管在 Capslock 亮燈與否都能輸入中文

**替代方案**

沒有替代方案，由於太常誤觸，已換回超注音輸入法。
可能存在的替代方案是利用其他軟體達成每次點擊左 shift 即重置 Capslock，使其不亮燈

**其他**

希望你們可以為廣大的 windows 使用者開發出一款真正和 windows 輸入習慣相同的中文輸入法，讓我們徹底擺脫蘋果自作主張要用戶改變的習慣
若能如此，我甚至希望能付費使用支持開發團隊

**Comment by ShikiSuen** [comment]
已經新增至備忘清單：https://github.com/vChewing/vChewing-macOS/issues/490

**Comment by ShikiSuen** [comment]
> 可能存在的替代方案是利用其他軟體達成每次點擊左 shift 即重置 Capslock，使其不亮燈

我備忘一下：https://stackoverflow.com/questions/30035131/simulate-toggle-caps-lock-programatically-in-os-x

**Comment by ShikiSuen** [comment]
@a0972199950 
知會一件事情。

你要求「提供選項，關閉『當 Capslock 亮燈時改為英文小寫輸入』」，這個倒是可以實作。
但因為「Shift 中英文切換功能在 CapsLock 亮燈時無效」，導致這裡的習慣體系注定無法「真正和 windows 輸入習慣相同」。

這與您在這個工單當中的一開始的需求陳述相違，還請知悉。

**Comment by a0972199950** [comment]
> @a0972199950 知會一件事情。
> 
> 你要求「提供選項，關閉『當 Capslock 亮燈時改為英文小寫輸入』」，這個倒是可以實作。 但因為「Shift 中英文切換功能在 CapsLock 亮燈時無效」，導致這裡的習慣體系注定無法「真正和 windows 輸入習慣相同」。
> 
> 這與您在這個工單當中的一開始的需求陳述相違，還請知悉。

理解，我認為能提供一個這樣的選項對使用者總是好的
至於 shift 切換，目前有 karabiner-elements 的替代方案可以使用，並且此替代方案還剛好解決了無法在實際輸入前得知當下究竟是英文或是中文的痛點

蘋果輸入法最大的問題，就是不提供任何方案，要求使用者反過來自適應他們。不管他們的目的為何，能有一個第三方輸入法把選擇權從蘋果手裡還給使用者，我覺得都是極其可貴價值

**Comment by ShikiSuen** [comment]
@a0972199950 

你不妨也去 Twitter 跟 XHacker 私訊把這些吐槽都講一遍。他在輸入法組。
受 Apple 公司內部規定，他無權擅自對外承諾「一個產品問題是否會得到解決」，也很可能不會有任何回應。但他會看見。

**Comment by ShikiSuen** [comment]
@a0972199950 噩耗：這個特性已經開發完畢，但我只是（在特定選項開啟時）取消了威注音對 CapsLock 亮燈時的英文輸出處理。

如果您在使用過程當中發現仍舊只能打英文的話，那是系統行為所致。我目前無解。這種情況發生的機率並非百分之百。

**Comment by ShikiSuen** [comment]
3.6.1 版已經發佈。
