### ISSUE TITLE
[功能建議] 請問是否有機會提供選項關閉透過<shift>切換中英模式時的通知飄窗

### ISSUE THREAD

**Issue by charliie-dev** [ShikiSuen/vChewing-CHS#493]
**痛點**
透過\<shift\>切換中英模式時的通知飄窗影響注意力, 希望能盡量減少視覺噪音.

**功能說明**
在偏好設定中新增"關閉飄窗通知"的選項, 使透過任何形式切換輸入法時沒有飄窗通知.

**替代方案**
無

**其他**
今天第一天使用威注音, 輸入上確實是比小麥注音好用多了 還提供中文輸入下的半形符號, 個人非常需要, 非常感謝團隊!

**Comment by ShikiSuen** [comment]
macOS 14 系統內建的輸入法上下文指示器可是無法顯示威注音的 Shift 中英文輸入狀態的。
除了飄窗以外，就產品特性設計而言，我實在不知道該怎樣讓使用者在此時知道自己的鍵盤中英文輸入狀態。

至於那些包括康熙繁體等模式的飄窗通知，也要關掉嗎？

**Comment by ShikiSuen** [comment]
總之，關掉飄窗通知的功能可以做，但必須得有替代方案。
我不知道像是「macOS 內建的 系統音量大小調整時的那種 toast 顯示」是否屬於您可以接受的範圍。

**Comment by charliie-dev** [comment]
> macOS 14 系統內建的輸入法上下文指示器可是無法顯示威注音的 Shift 中英文輸入狀態的。

原來如此, 試了一下的確不行.

> 除了飄窗以外，就產品特性設計而言，我實在不知道該怎樣讓使用者在此時知道自己的鍵盤中英文輸入狀態。

個人而言, 我按shift切換中英文時主要場景為在一段中文中插入幾個英文單詞, 很快又會切換回來. 切換頻率相對打整段中文或英文時高很多, **我個人認為**這時候當下輸入狀態似乎可以不用提示?  簡單來說, 我是認為切換時間非常短, 使用者應該是會記得他們當下的輸入狀態, 不需要另外有提示(個人經驗, 也跟windows注音輸入法shift切換中英時類似, 不知道符不符合您的設計理念)

> 至於那些包括康熙繁體等模式的飄窗通知，也要關掉嗎？

雖然我個人目前還沒有使用到康熙繁體等功能, 但這類比較特殊的字模模式, 我覺得應該也可以給使用者有個選項去開關飄窗通知.

我個人認為比較合適的客製化飄窗通知設定分類:
1. capslock 切換輸入法可以選擇要不要開啟飄窗通知(如目前已有的設定)
2. shift 切換中英是否要飄窗通知
3. 特殊字模模式是否要飄窗通知

三個notify toggle也許比較make sense?

不曉得您的想法如何

> 我不知道像是「macOS 內建的 系統音量大小調整時的那種 toast 顯示」是否屬於您可以接受的範圍。

如果可以都沒有通知的話最好哈哈, 但如果必須要選的話我認為toast形式會比飄窗通知好, 因為飄窗通知會讓我一直誤以為有訊息跳出來了XD, toast形式相對比較不會

**Comment by ShikiSuen** [comment]
感謝您的意見反饋。那我抽空弄一下 Toast。
接下來這版更新可能有點晚，且不是所有計畫要引入的修改都會在 3.6.1 版實作。
搞不好得等到下個月才能出 3.6.1。

**Comment by charliie-dev** [comment]
感謝!

**Comment by ShikiSuen** [comment]
@CharlesChiuGit 不會。另外我還有個方案，不知您怎麼看：

仍舊是飄窗通知，但飄窗的位置改到螢幕右下角。

**Comment by charliie-dev** [comment]
有機會是可以有一些選項的嗎? 如:

- 使用左/右側的Shift鍵切換英數輸入模式時, 以右上飄窗通知
- 使用左/右側的Shift鍵切換英數輸入模式時, 以右下飄窗通知
- 使用左/右側的Shift鍵切換英數輸入模式時, 以toast形式通知
- 關閉使用左/右側的Shift鍵切換英數輸入模式時之輸入法提示通知

這樣會不會比較好?

**Comment by ShikiSuen** [comment]
@CharlesChiuGit 

問題是做選項是最浪費時間的，因為偏好設定有兩個體系：XIB 體系（負責 macOS 10.9 至 12）以及 SwiftUI 體系（macOS 13 開始）。

SwiftUI 版偏好設定視窗最近放棄了 macOS 10.15 至 12 的支援，因為有些特性剛需 macOS 13 開始的 API。

XIB 視窗是最麻煩的，再加上簡繁日英四語翻譯，就又更麻煩了。而且 XIB 視窗的版本還要單獨組譯出一個視窗到 macOS 10.9 Mavericks 虛擬機內實際測試每一次修改是否正常工作。

所以，講真心話，我實在不想再多新增任何開關了。真的太累。

不然這個工單推遲處理好了，眼下有更著火的故障應對機制要推送，因為總是有第三方 app 濫用 SecureEventInput 導致威注音無法正常工作、然後就有使用者來抱怨說是威注音的故障。

**Comment by charliie-dev** [comment]
了解QQ 不好意思辛苦了 那我支持改成右下飄窗 也可以推遲處理 這不算是功能性上的故障 感謝大大!

**Comment by ShikiSuen** [comment]
剛剛決定 3.6.1 版的通知飄窗位置還是螢幕右上角，但位置向下偏移了一些、與系統的訊息通知的位置不重疊。
![image](https://github.com/vChewing/vChewing-macOS/assets/3164826/0c75b995-e18c-476b-a3d9-75bf9df7b129)

**Comment by ShikiSuen** [comment]
> 也跟windows注音輸入法shift切換中英時類似

完全不類似：Windows 10 有兩個輸入法圖示，其中一個專門用來顯示中英狀態。而 macOS 只有一個輸入法圖示。
（有些輸入法的額外的中英圖示是各自自行實作的，但在原理上只要這些輸入法沒叫出來過就不會顯示。而且 macOS 的頂端選單列的空間寸土寸金。）

**Comment by ShikiSuen** [comment]
3.6.1 已經發佈。

**Comment by ShikiSuen** [comment]
該工單暫時關閉。
威注音目前的行為是讓輸入法自身的飄窗通知的顯示位置向下錯位了一些距離、使得其不與系統的新訊息重疊。
這應該可以變相解決樓主在困擾的問題。

**Comment by charliie-dev** [comment]
> 該工單暫時關閉。
> 
> 威注音目前的行為是讓輸入法自身的飄窗通知的顯示位置向下錯位了一些距離、使得其不與系統的新訊息重疊。
> 
> 這應該可以變相解決樓主在困擾的問題。

感謝，目前這種狀態已經算解決當初困擾了。
