### ISSUE TITLE
[功能建議] 改善威注音在 macOS Sonoma 輸入法切換器中的圖示

### ISSUE THREAD

**Issue by wzxu** [ShikiSuen/vChewing-CHS#507]
一張圖勝過千言萬語：
<img width="500" alt="chew" src="https://github.com/vChewing/vChewing-macOS/assets/5619348/060c92e5-bd64-46f9-8eb4-137707452aa4">
可以看見威注音的圖示和其他系統輸入法相鄰，有點格格不入，希望可以改成無背景的「ㄋ」或「威」字；
不確定和選單列的圖示有沒有關聯，不過那邊我是一向隱藏，眼不見為淨，所以不是這次的回報重點。

**Comment by ShikiSuen** [comment]
@wzxu 我也想改啊，但 Apple 不給出任何 documentation 我開工單催了幾個月都沒用啊。
這個 issue 我先留著 open，會持續關注這個問題在 Apple Developer Relations 那邊的 DTS 工單的追蹤情況。

**Comment by ShikiSuen** [comment]
現在的問題是：這個 input source indicator icon 直接用了 menuicon，而第三方輸入法開發者完全不知道該怎樣分別指派 icon。

**Comment by ShikiSuen** [comment]
喔對，你那張圖無法區分威注音的簡體模式與繁體模式。

**Comment by ShikiSuen** [comment]
@wzxu 請洽這篇推文：https://twitter.com/vChewingIME/status/1740401077403677035

**Comment by ShikiSuen** [comment]
這個工單我先關掉了。回頭 Apple 要是對此有跟進的話，這個工單可以再開啟、再繼續處理。
目前的輸入法選單與輸入法上下文指示器當中的共用圖示如下：
<img width="288" alt="image" src="https://github.com/vChewing/vChewing-macOS/assets/3164826/87b43cb1-b3b3-4cc2-a4ee-eec069ccaccf">
