### ISSUE TITLE
[功能建議] 安裝的時候不要自動將簡體中文鍵盤打開

### ISSUE THREAD

**Issue by larryjclai** [ShikiSuen/vChewing-CHS#511]
**免責聲明**

威注音輸入法保留拒絕任何種類的功能建議的權利（本來就有）。

閱讀來自各位使用者的功能建議請求，是一回事；**但**威注音研發方怎樣利用這些建議請求背後的潛在資訊、來制定威注音接下來的研發方向（或可能棄用相關想法），則是**另一回事**。

**痛點**
現在每次更新的時候他都會自動把簡體輸入法打開，我都要在進去鍵盤裡面做移除。希望能夠改掉這個預設值。

**其他**
威注音真的很好用，現在完全離不開了！

**Comment by ShikiSuen** [comment]
@larryjclai 不啟用這個簡體中文模式的話就無法做繁簡模式切換，請問你是否仍要這樣做？

**Comment by ShikiSuen** [comment]
@larryjclai 這個工單恐無法應對。

按理來講，這個功能是「可以正常實作的」。

然而，macOS 12 開始，TISInputSource 當中的 kTISPropertyInputSourceIsEnabled 會在對應的輸入法**尚未被使用者加到輸入法選單**的時候**謊報這個情況**，使得第三方輸入法開發者無法藉由程式手段判斷「一個輸入法是否真的有被使用者加到輸入法選單內」。

於是，在製作安裝程式的時候，就只能強行自動安裝所有的輸入模式。請諒。
