### ISSUE TITLE
[bug]自動選字問題

### ISSUE THREAD

**Issue by ayii0111** [ShikiSuen/vChewing-CHS#515]
**摘要**
自動選字，有時候有效有時候沒效，例如「未固化」這個詞
有時候會變成「位固化」可我明明沒有使用過這樣錯誤的詞
而且有時候明明升權，那個字卻好像沒有升權成功，用愈久選字問題愈多
**快速分類**
請問您遇到的是：
[自動選字錯誤]

**Comment by ShikiSuen** [comment]
@ayii0111 你先編輯一下使用者辭典刪掉你近期針對這種情況新增的升權資料（簡體中文辭典與繁體中文辭典都要做這個處理）。

然後，利用 Shift+前後方向鍵 來就地標記整個新詞來加入即可。
<img width="323" alt="image" src="https://github.com/vChewing/vChewing-macOS/assets/3164826/f4976abf-f39a-4616-8d3f-1fbf8542343b">

**Comment by ShikiSuen** [comment]
該工單暫時關閉。
