### ISSUE TITLE
【待辦】得允許大鍵盤右側數字鍵區繞過組音區直接與組字區交互。

### ISSUE THREAD

**Issue by wayneljw** [ShikiSuen/vChewing-CHS#517]
原始工單標題：

# [功能問題提報]使用全尺寸鍵盤，按右側數字鍵，組字區內容就會馬上被送出

請問您遇到的是：
- [x] 其他：輸入法行為的小問題。

例如我要輸入「這是二（2）」。
我先把括弧「（）」輸入好之後，再將游標移回括弧內來輸入內容。
如果括弧內是輸入中文就沒問題，但如果是「以全尺寸鍵盤按右側數字鍵來輸入數字」，組字區就會馬上被提交，並且數字沒有出現在預期的位置。

**操作流程：**
* 在組字區輸入「這是二（）」
* 按「←左鍵」，將組字區游標移到「（」與「）」的中間
* 按全尺寸鍵盤右邊數字鍵的「2」

**預期結果：**
* 組字區顯示「這是二（2）」，並且游標停在「2」與「）」中間。組字區未被送出。

**實際結果：**
* 組字區被送出，在文檔上出現「這是二（）2」。

**說明：**
上述在括弧裡若輸入中文，就不會有這個問題。
只有在按右側數字鍵的時候才會出現此問題。
事實上，不僅是括弧，一般輸入中文過程裡，如果按游標回到前面去輸入數字，都會發生「組字區馬上被送出，並且數字出現在最後」的情形。
會發現這個問題是因為通常在輸入成對的標點時（括弧、引號），都會習慣先整組輸入完，再用游標退回去輸入括弧的內容。

**系統環境：**
- 威注音版本：3.7.2
- 注音排列與基礎鍵盤佈局：大千排列
- macOS 版本：14.2.1（23C71）
- 在哪個應用程式中打字遇到問題：所有應用程式
- 電腦機種：MacBook M2 Pro
- 其他特殊設備：有外接螢幕、外接USB全尺寸鍵盤
- 特殊設定：無

**Comment by ShikiSuen** [comment]
這是威注音的故意設計，以應對 Excel 使用者對數字的便捷輸入需求。
但現在來看恐怕需要對 NumPad 做一個追加開關、允許 NumPad 繞開組音區直接輸入符號與標點。

這個功能恐怕會推遲到二月底才能有機會實裝。在此之前的更新很可能不會有時間實裝與此功能有關的變動。
這段時間內您可以改用這樣的方法：

https://github.com/vChewing/vChewing-macOS/assets/3164826/4389a798-ce41-4154-8efa-4f5070ada8f1

**Comment by ShikiSuen** [comment]
@wayneljw 請問您希望 在按照您期許的方式輸入的數字 是全形還是半形？

**Comment by ShikiSuen** [comment]
Proposal:
```
テンキーで入力可能の文字 / 數位小鍵盤的可輸入字元 / Printable Chars in Numeric Pad

- 半角でそのまま送り出す / 以半形文字直接遞交 / Commit directly (half-width)
- 入力緩衝列に半角文字を挿入 / 以半形文字插入組字區 / Insert into composition buffer (half-width)
- 入力緩衝列に全角文字を挿入 / 以全形文字插入組字區 / Insert into composition buffer (full-width)
```
後兩個選項對應的原廠辭典的檢索前綴碼都是「`_NumPad_`」開頭，但會對全形候選字與半形候選字動態地給出不同的權重（根據上述使用者篇害設定而做出對應的變動）。可以使用候選字輪替鍵切換（組字區內的）單個文字的全半形。

----------

得給 LangModelAssembly 引入一個專門用來處理 NumPad 的函式。

**Comment by ShikiSuen** [comment]
<img width="1577" alt="image" src="https://github.com/vChewing/vChewing-macOS/assets/3164826/6a75d6dc-62e5-4207-a452-cfb4c8d18134">
已針對語言模組總成部件將數字鍵盤區的資料補給特性實作完畢。
接下來找時間給輸入法本體對接實作這個功能。

**Comment by wayneljw** [comment]
@ShikiSuen 謝謝您的回覆。

從影片上來看，您是使用了option按鍵搭配上方數字鍵在組字區輸入數字，是嗎？我現在才知道可以這樣輸入，也是一個解決辦法。

另回覆：一般我使用右側數字鍵的時候，都是輸入半形。但如果這個設定未來會成為一個設定選項，倒是可以考慮讓使用者自行決定。

您稍早提到的「這是威注音的故意設計，以應對 Excel 使用者對數字的便捷輸入需求。」
確實沒錯，在「中文輸入法的狀態下」，使用者是會希望在儲存格裡直接按右側的數字鍵來快速輸入數字。
我測試了一下，目前的行為是：
* 如果組字區是空的（還沒輸入文字資料），直接用全尺寸鍵盤右側輸入數字，或是「SHIFT+英文」，就會直接輸入英文、數字。
* 如果組字區有資料，用「SHIFT+英文」輸入英文時，會依據「Shift+字母鍵」設定裡的行為來執行。
* 如果組字區有資料，用右側數字鍵輸入數字時，會直接遞交。

從上述來看，「Shift+字母鍵」有設定可以控制其行為。但數字鍵沒有。

因此，不知道是否您認同以下的歸納：
* 「SHIFT+英文」的設定，其實是一般使用者在「混搭中、英輸入」時，所習慣的行為。
* 同一個人在「混搭中、英、數輸入」時，可能也會與「混搭中、英輸入」有類似的習慣。
* 因此，我們可以模仿「SHIFT+英文」的設定，另製作一個「全尺寸鍵盤右側數字鍵」的設定值，裡面有五個選項：
    * 直接鍵入內文組字區
    * 始終直接遞交半形數字
    * 始終直接遞交全形數字
    * 直接遞交半形數字，除非組字區不為空
    * 直接遞交全形數字，除非組字區不為空

<img width="451" alt="2024-01-27_23-24-05" src="https://github.com/vChewing/vChewing-macOS/assets/1362564/f184e6ee-c89e-431e-b229-f5c2c106fde8">

另請問，您是否有考慮在威注音官網，或是github提供贊助功能？

**Comment by ShikiSuen** [comment]
@wayneljw 論及贊助功能的方法途徑，我還在考量中。
我居住在中國大陸，你們熟悉的贊助方式多半不適用。

**Comment by ShikiSuen** [comment]
@wayneljw 我前面的留言回覆裡面有個 proposal，就是想要增加一個這樣的選項。這裡贅述一下：
```
下拉選單「數位小鍵盤的可輸入字元」內建三個選項：
「以半形文字直接遞交」「以半形文字插入組字區」「以全形文字插入組字區」。
```
不知這是否與您的歸大一致。

**Comment by ShikiSuen** [comment]
@wayneljw 您的歸納我看明白了。那就相當於多出兩個選項。這樣也可以。

**Comment by ShikiSuen** [comment]
更新一下 proposal：
```swift
    case .kNumPadCharInputBehavior: return .init(
        userDef: self, shortTitle: "Printable Chars in Numeric Pad:", // テンキーで入力可能の文字 / 數字小鍵盤的可輸入字元
        description: "Choose the behavior of numeric pad inputs.", // テンキー文字の入力行為をご指定ください。 // 指定數字小鍵盤的輸入行為。
        options: [
          0: "Always directly commit half-width chars", // いつでも半角で直接出力 / 始終以半形文字直接遞交
          1: "Always directly commit full-width chars", // いつでも全角で直接出力 / 始終以全形文字直接遞交
          2: "Insert into composition buffer (half-width)", // 入力緩衝列に半角文字を挿入 / 以半形文字插入組字區
          3: "Insert into composition buffer (full-width)", // 入力緩衝列に全角文字を挿入 / 以全形文字插入組字區
          4: "Directly commit half-width chars only if the compositor is empty", // 入力緩衝列がからっぽの時、半角で直接出力 / 直接遞交半形文字，除非組字區不為空
          5: "Directly commit full-width chars only if the compositor is empty", // 入力緩衝列がからっぽの時、全角で直接出力 / 直接遞交全形文字，除非組字區不為空
        ]
      )
```

**Comment by ShikiSuen** [comment]
該功能針對主流版本的內容已經實作完畢，只剩下 Aqua 紀念版專用的（針對 macOS 10.9 的）偏好設定介面需要實作。
回頭會隨 3.7.3 版更新推送。
<img width="601" alt="image" src="https://github.com/vChewing/vChewing-macOS/assets/3164826/b46e48f8-efa6-414e-9660-4719e2f43639">

**Comment by ShikiSuen** [comment]
全部實作完畢。
<img width="1461" alt="image" src="https://github.com/vChewing/vChewing-macOS/assets/3164826/6c4f11fd-d95b-41e2-807f-7f7c6c8060ff">

**Comment by ShikiSuen** [comment]
Dealt.
