### ISSUE TITLE
[功能建議] 輸入「愛」時可以選像原生的注音輸入法一樣的 emoji

### ISSUE THREAD

**Issue by griiid** [ShikiSuen/vChewing-CHS#526]
**痛點**
請告訴我們為什麼目前威注音沒辦法解決您的問題。您可以講一個能讓讀者得以感同身受的小故事，比如：

- 我前兩年有使用小麥輸入法，最大的痛點是選字有很多 emoji 不像原生一樣方便。
- 今年換了新電腦後，因為還是想用打字的方式輸出很多 emoji，所以先用原生的注音輸入法，但他的選字真的是爛到極致（連極致也不認得...）

**功能說明**
原生的注音輸入法輸入「愛」時的選字有這兩個 emoji：❤️、😮‍💨
我個人是需要 ❤️
原生注音輸入法選字截圖如下：

<img width="168" alt="截圖 2024-02-27 08 58 31" src="https://github.com/vChewing/vChewing-macOS/assets/17796098/f4df68f5-9613-4b96-8656-225ef5c8d823">

**替代方案**
開 emoji 來打

**其他**
謝謝你們，加油

**Comment by ShikiSuen** [comment]
@griiid 
離下一版威注音發佈還有一段時間。在此之前您可以這樣自己加：
<img width="678" alt="image" src="https://github.com/vChewing/vChewing-macOS/assets/3164826/84beef5f-1c31-4c32-8693-edd49c911bf6">

然後叫出選字窗之後往前翻一頁就能看到了：
<img width="496" alt="image" src="https://github.com/vChewing/vChewing-macOS/assets/3164826/7436a891-ec8e-47b5-b4b8-3047f43217c5">

**Comment by ShikiSuen** [comment]
另外呢，輸入法內建 Emoji 其實是個雙刃劍、也是個很難吃力討好的事情。

一是 Emoji 的種類與數量隨著 Unicode 版本更迭而越來越多、數量非常空前，但一個 Emoji 可能會有好多個中文稱謂（加上兩岸審音的差異導致的唸法不同）……這些語料都需要一個個地人工去補，就很麻煩。

二是有些接收文字輸入的軟體對 Emoji 的相容性很爛，甚至像 Acrobat 那樣「內文組字區出現了 Emoji 就會直接讓軟體本身炸掉」的情況。這也是為什麼威注音允許徹底關掉這些 Emoji 候選字在選字窗當中的顯示。

以上。總之請善用我剛才提到的繪文字符號編輯功能。

**Comment by ShikiSuen** [comment]
該工單暫時關閉。有想法或追加提問的話可以再留言。
