### ISSUE TITLE
[功能問題提報] 無法切換、設定輸入法模式

### ISSUE THREAD

**Issue by patyhank** [ShikiSuen/vChewing-CHS#529]
### **請在開新的工單之前閱讀《[故障提報與用儀器捉蟲](https://vchewing.github.io/BUGREPORT.html)》按照裡面的方法整理相關資訊、且在開工單之後電郵知會我。因各種可能原因，威注音的主程式師可能無法隨時收取 GitHub 與 Gitee 的工單提醒訊息。**

**摘要**
不確定是什麼因素（疑似是螢幕或解析度）導致，於桌面最上方的輸入法欄位中，威注音下方僅顯示不可選取的「.......」

**快速分類**
請問您遇到的是：

- [ ] 輸入法崩潰或正在接受文字輸入的應用程式崩潰
- [ ] 輸入法叫不出來，或無法正確敲出中文
- [x] 無法切換至特定功能的啟用/停用狀態
- [ ] 輸入法效能有問題（執行速度太慢/電腦發燙）
- [x] 輸入法應用程式介面顯示不正常（IMK 選字窗的應用介面美術瑕疵恕不受理，因為是 Apple 負責的）
- [ ] 輸入法亂放屁（請確保偏好設定內的廉恥模式的勾沒有被去掉）
- [ ] 其他

**問題發生步驟**
請問您是怎麼遇到這個問題的？像是：

1. 重新開機
2. 初次點開選單時可正常選擇設定
3. 切換輸入法後再次點開來就無法正常顯示

**預期正常狀況**
可正常進行設定、模式選擇

**螢幕截圖或螢幕錄製**
<img width="218" alt="image" src="https://github.com/user-attachments/assets/42b42ab5-5987-42d1-b976-ea2497287fd7">

**電腦環境**
請問您在怎樣的環境遇到這個問題？

- 威注音版本：3.8.6
- 注音排列與基礎鍵盤佈局：
- macOS 版本：版本14.6（23G80）
- 在哪個應用程式中打字遇到問題：打字沒有問題
- 電腦機種：Apple M2 Mac Mini
- 其他特殊設備：螢幕解析度是（3440 × 1440）
- 特殊設定：

**其他**
我有嘗試把螢幕換成小一點的1920x1080，選項就可以正常跑出來，但依然無法進行互動

**Comment by patyhank** [comment]
我找到原因了，是Minecraft導致的，執行中選項會無法使用
關掉就正常了，但不知道問題是出在哪

**Comment by ShikiSuen** [comment]
@patyhank 那問題肯定是 Minecraft 了。
