### ISSUE TITLE
無限聯想詞的侷限性（恐涉及整個詞庫系統的改良）。

### ISSUE THREAD

**Issue by ShikiSuen** [ShikiSuen/vChewing-CHS#91]
v1.8.4 發行之後，我已經安排了一個新的功能更新。

這個功能更新會在選擇超過三個字的聯想詞結果（也就是追加至少兩個漢字）時、自動以該候選內容的最後一個漢字、來檢索是否有對應的聯想詞在庫。

這樣一來就可以實現無限聯想連鎖。
但這個功能在檢索時是沒辦法帶上讀音的，於是檢索不到那些以讀音為索引的聯想詞記錄。

於是又回到了「怎樣將系統預設的原廠詞庫弄成可以直接被聯想詞系統動態利用的詞庫」的問題上來。
這要求辭庫內擁有多種形式的索引方式。目前的 plist 辭庫恐怕無法做到這一點。

看來是時候檢討是否需要引入 SQLite 了，只是我對 SQLite 狗屁不通。

**Comment by pan93412** [comment]
也不一定要精熟 SQLite 的 SQL 語法，可以搭配 ORM 之類的組件方便開發。

不過我沒有 Swift 開發經驗，不清楚這套 ORM 是否好用。

## ORM 名單（由 Star 高低排序）

- https://github.com/groue/GRDB.swift
- https://github.com/Kitura/Swift-Kuery-ORM
- https://github.com/ZeeQL/ZeeQL3
- https://github.com/fnc12/sqlite-orm-swift

**Comment by ShikiSuen** [comment]
@pan93412 威注音目前對原廠辭典的處理方法與小麥有差異。

小麥那邊 Lukhnos Liu 喜歡用 C++ 玩指針，他寫出的 ParselessLM 可以對 txt 單遍讀取就能完成載入、卻要求所有索引鍵必須按照 Unicode 排序。

威注音在將語言模組與資料模組 Swift 重寫的時候，一開始也是用 txt parsing，卻發現效率非常低下。Isaac Xen 想到了模擬 C++ StringView 的方法，但該方法會牽涉到大量的矩陣運算、對 2017 年之前的電腦極端不友好（會導致輸入法需要二十秒才能載入完畢、而 mac mini 2018 就可以一秒搞定，體驗不一致）。所以威注音就換了 Plist 格式的詞庫、以便在 2011 年的機種內也可以實現「只需一秒就可以載入詞庫」。

但是，Plist 的弊端就是能存儲的資料類型有限，且其索引是死的。我是不知道怎樣將 Swift 的自定義 Codable 資料類型弄成可以讓 Plist 存取的形式。好像 Plist 本身也不支援「對單筆資料引入不同種類的 key」。

**Comment by ShikiSuen** [comment]
回頭改用這套好了：https://github.com/stephencelis/SQLite.swift

**Comment by ShikiSuen** [comment]
Code Data 也是一個可選項：https://www.tpisoftware.com/tpu/articleDetails/2448

**Comment by ShikiSuen** [comment]
這些 ORM 都不錯，今後或許能派上用場。
這個工單先作廢。
