### ISSUE TITLE
[1.8.6] 選字會讓威注音閃退

### ISSUE THREAD

**Issue by MiliChang** [ShikiSuen/vChewing-CHS#93]
環境: macOS Monterey 12.5
晶片: m1
版本: 1.8.6
描述:
在兩個中文字以上進行選字時會讓威注音崩潰重新啟動，重新啟動後無法正確輸入聲調，需要切換回英文再切回威注音才會正常。
嘗試過降版本，直到 1.7.4 還是有此問題。移除後重新安裝 1.8.6 也有問題。
之前使用都是正常的，有沒有可能是最近更新了 macOS 到 12.5 導致的....

**Comment by ShikiSuen** [comment]
@MiliChang 首先感謝您來這裡開工單。
其次呢，根據您問題的描述，這個問題恐怕需要您提供 backtrace 檔案（以 .ips 結尾）、或者 Xcode Instruments 抓取記錄。
這篇文章內有詳細的操作說明：https://vchewing.github.io/BUGREPORT.html
如果只是 ips 檔案的話，也可以直接將其正文貼在這個工單下（以回覆的形式）。

唯有這樣，我才可能分析出來到底是在哪個程式階段出了差錯。

P.S.: 我手頭沒有 Apple Silicon 的機種，不過估計應該沒差。

**Comment by ShikiSuen** [comment]
備忘：已接獲來自 Intel 機種使用者的雷同災情報告。

**Comment by DenniesChangWT** [comment]
我遇到同樣的情況, 系統是 macOS 12.5 2019版 16" MBP Intel CPU, 附上 ips 檔.

[vChewing_1.86_b1986_macOS12.5_Intel.zip](https://github.com/vChewing/vChewing-macOS/files/9238661/vChewing_1.86_b1986_macOS12.5_Intel.zip)

**Comment by ShikiSuen** [comment]
@DenniesChangWT @MiliChang 
請二位點開輸入法選單，摁住 Alt(Option) 再點一下輸入法選單內的「清除臨時記憶語彙資料」然後再次嘗試。

**Comment by MiliChang** [comment]
「清除臨時記憶語彙資料」清除後便正常，感謝您。
真的是最好用的 Mac 輸入法，再次感謝！

**Comment by ShikiSuen** [comment]
@MiliChang 哪裡，是您不嫌棄。如果接下來一週之內還有異常的話，請再提報。
（我最近有將半衰記憶模組改為「經過一次半衰才會記憶」，首次半衰大概需要一天左右的樣子。）

**Comment by ShikiSuen** [comment]
問題初步調查結果。
macOS 12.5 更新可能會導致威注音輸入法位於下述目錄的使用者半衰記憶模組檔案損毀：
```
/Users/使用者帳戶名稱/Library/Application Support/vChewing/override-model-data-chs.dat
/Users/使用者帳戶名稱/Library/Application Support/vChewing/override-model-data-cht.dat
```
**以下內容只是推論**
當檔案損毀時，每次敲字手動選字時觸發的觀測行為便無法順利執行，因為觀測會觸發檔案寫入操作。

威注音下一個版本更新會引入一個救援機制。
如果這種因為壞檔而導致的問題發生過一次的話，輸入法因此被動重新啟動時、會感知到這個情況。
屆時會自動同時清除簡體中文與繁體中文兩個模式下的半衰模組的存檔內容。

這個工單我過一週再關。

備註：威注音 v1.7.4 版並未引入與半衰模組有關的更新，而緊接著這個版本的威注音 v1.8.0 只是將半衰模組存檔目錄。

**Comment by ShikiSuen** [comment]
補記＆備忘：

問題可能出現在這個觀測用函數的內部的其它地方，至少是：讀入的既有資料不能正常被該函數處理。
如果真的是在存檔時出錯的話，堆棧追蹤頂端應該是「mgrLangModel.saveUserOverrideModelData()」這個函數才對。
<img width="795" alt="image" src="https://user-images.githubusercontent.com/3164826/182298399-ed80dafd-865f-420f-9267-80a73a989a25.png">

先引入災後自動救援機制，回頭有時間再慢慢調查這個函數內究竟出了什麼情況。

**Comment by ShikiSuen** [comment]
v1.8.7 版已經發佈，引入了災後救援機制。
同樣的問題再次發生的話，不會連續發生，而是會出現這個系統通知：
![image](https://user-images.githubusercontent.com/3164826/182411309-e540fbae-eed3-4a68-b283-61fd1f8fff12.png)
且有問題的半衰記憶資料會被自動清空。

**Comment by ShikiSuen** [comment]
一週之內沒有相關追加提報，故關閉該工單。

（預定於 8 月 10 日之前發佈的）威注音 v1.9.0 對使用者半衰記憶模組有行為調整。
如果在使用該版本時有收到觀測時崩潰的報告的話，請再開工單、且附上問題發生時產生的 ips 檔案。
