### ISSUE TITLE
偏好設定的「體驗」頁面面積佔用太大：要麼改成捲動，要麼拆成兩頁。

### ISSUE THREAD

**Issue by ShikiSuen** [ShikiSuen/vChewing-CHS#98]
偏好設定的「體驗」頁面面積佔用太大。
這對 1024x768 解析度下的使用體驗構成毀滅性的打擊。
要麼改成捲動，要麼拆成兩頁。

**Comment by windwords** [comment]
个人感觉改为滚动比拆成两页更好 
:)

**Comment by ShikiSuen** [comment]
@windwords 也是。回頭我找一找看看 AppKit 有沒有辦法把 View 在視窗內顯示成捲動樣式的方法。

其實這並非急需解決的問題，因為威注音目前無論 SwiftUI 新版偏好設定視窗還是 XIB 舊版設定視窗都不會在 1024x768 螢幕解析度下被 Dock 擋住。

**Comment by ShikiSuen** [comment]
SwiftUI 版偏好設定內容已經改成捲動形態。
XIB 版的偏好設定應該不會再有什麼變化了。
